export const configSections = [
  { key: 'site', title: '站点设置', icon: 'Globe2', description: '站点名称、网址、注册、试用与货币设置。', fields: [
    { key: 'app_name', label: '站点名称' }, { key: 'app_description', label: '站点描述', type: 'textarea' },
    { key: 'app_url', label: '站点网址', placeholder: 'https://example.com' }, { key: 'subscribe_url', label: '订阅 URL', help: '多个地址使用英文逗号分隔，留空使用站点网址。' },
    { key: 'logo', label: 'LOGO 地址' }, { key: 'tos_url', label: '用户条款 URL' },
    { key: 'force_https', label: '强制 HTTPS', type: 'boolean' }, { key: 'stop_register', label: '停止新用户注册', type: 'boolean' },
    { key: 'ticket_must_wait_reply', label: '工单等待回复限制', type: 'boolean' }, { key: 'try_out_plan_id', label: '试用套餐 ID', type: 'number' },
    { key: 'try_out_hour', label: '试用时长（小时）', type: 'number' }, { key: 'currency', label: '货币单位', placeholder: 'CNY' }, { key: 'currency_symbol', label: '货币符号', placeholder: '¥' },
  ] },
  { key: 'subscribe', title: '订阅设置', icon: 'Rss', description: '套餐变更、流量重置、订阅路径和提醒线路。', fields: [
    { key: 'plan_change_enable', label: '允许用户更改订阅', type: 'boolean' }, { key: 'surplus_enable', label: '开启套餐折抵', type: 'boolean' },
    { key: 'reset_traffic_method', label: '全局流量重置方式', type: 'select', options: [{ value: 0, label: '每月 1 日' }, { value: 1, label: '按月重置' }, { value: 2, label: '不重置' }, { value: 3, label: '每年 1 月 1 日' }, { value: 4, label: '按年重置' }] },
    { key: 'subscribe_path', label: '订阅路径', help: '修改后订阅地址会改变。' }, { key: 'show_info_to_server_enable', label: '订阅中展示用户信息', type: 'boolean' },
    { key: 'show_protocol_to_server_enable', label: '线路名称显示协议', type: 'boolean' }, { key: 'default_remind_expire', label: '默认开启到期提醒', type: 'boolean' },
    { key: 'default_remind_traffic', label: '默认开启流量提醒', type: 'boolean' }, { key: 'subscribe_unavailable_tip_enable', label: '自定义不可用提醒', type: 'boolean' },
    { key: 'subscribe_unavailable_tip_lines', label: '提醒线路内容', type: 'textarea' }, { key: 'subscription_transfer_enable', label: '允许套餐转让', type: 'boolean' },
    { key: 'subscription_transfer_fee', label: '套餐转让手续费（分）', type: 'number' }, { key: 'new_order_event_id', label: '新购事件 ID', type: 'number' },
    { key: 'renew_order_event_id', label: '续费事件 ID', type: 'number' }, { key: 'change_order_event_id', label: '变更事件 ID', type: 'number' },
  ] },
  { key: 'frontend', title: '前端设置', icon: 'Palette', description: '用户端主题、布局颜色和背景。', fields: [
    { key: 'frontend_theme', label: '用户端主题' }, { key: 'frontend_theme_sidebar', label: '侧栏风格', type: 'select', options: [{ value: 'light', label: '浅色' }, { value: 'dark', label: '深色' }] },
    { key: 'frontend_theme_header', label: '顶栏风格', type: 'select', options: [{ value: 'light', label: '浅色' }, { value: 'dark', label: '深色' }] },
    { key: 'frontend_theme_color', label: '主题颜色', type: 'select', options: [{ value: 'default', label: '默认' }, { value: 'darkblue', label: '深蓝' }, { value: 'black', label: '黑色' }, { value: 'green', label: '绿色' }] },
    { key: 'frontend_background_url', label: '登录背景 URL' },
  ] },
  { key: 'invite', title: '邀请与佣金', icon: 'UsersRound', description: '邀请注册、佣金确认、提现和三级分销。', fields: [
    { key: 'invite_force', label: '强制邀请注册', type: 'boolean' }, { key: 'invite_commission', label: '默认佣金比例（%）', type: 'number' },
    { key: 'invite_gen_limit', label: '邀请码创建上限', type: 'number' }, { key: 'invite_never_expire', label: '邀请码永不失效', type: 'boolean' },
    { key: 'commission_first_time_enable', label: '仅首次支付发放佣金', type: 'boolean' }, { key: 'commission_auto_check_enable', label: '佣金自动确认', type: 'boolean' },
    { key: 'commission_withdraw_limit', label: '提现门槛（元）', type: 'number' }, { key: 'commission_withdraw_method', label: '提现方式', type: 'lines', help: '每行一种提现方式。' },
    { key: 'withdraw_close_enable', label: '关闭提现', type: 'boolean' }, { key: 'commission_distribution_enable', label: '启用三级分销', type: 'boolean' },
    { key: 'commission_distribution_l1', label: '一级分销比例', type: 'number' }, { key: 'commission_distribution_l2', label: '二级分销比例', type: 'number' }, { key: 'commission_distribution_l3', label: '三级分销比例', type: 'number' },
  ] },
  { key: 'server', title: '节点配置', icon: 'ServerCog', description: '节点通讯密钥、同步频率和 WebSocket。', fields: [
    { key: 'server_token', label: '通讯密钥', type: 'password', help: '至少 16 位。' }, { key: 'server_pull_interval', label: '拉取间隔（秒）', type: 'number' },
    { key: 'server_push_interval', label: '推送间隔（秒）', type: 'number' }, { key: 'device_limit_mode', label: '设备限制模式', type: 'select', options: [{ value: 0, label: '严格模式' }, { value: 1, label: '宽松模式' }] },
    { key: 'server_ws_enable', label: '启用 WebSocket', type: 'boolean' }, { key: 'server_ws_url', label: 'WebSocket 地址', placeholder: '留空自动使用站点网址' },
  ] },
  { key: 'email', title: '邮件设置', icon: 'Mail', description: 'SMTP 服务与订阅提醒邮件。', action: 'mail', fields: [
    { key: 'email_host', label: 'SMTP 主机' }, { key: 'email_port', label: 'SMTP 端口', type: 'number' }, { key: 'email_username', label: 'SMTP 用户名' },
    { key: 'email_password', label: 'SMTP 密码', type: 'password' }, { key: 'email_encryption', label: '加密方式', type: 'select', options: [{ value: '', label: '无' }, { value: 'ssl', label: 'SSL/TLS' }, { value: 'tls', label: 'STARTTLS' }] },
    { key: 'email_from_address', label: '发件人地址' }, { key: 'remind_mail_enable', label: '启用到期/流量提醒邮件', type: 'boolean' },
  ] },
  { key: 'telegram', title: 'Telegram', icon: 'Send', description: '机器人通知、绑定引导和 Webhook。', action: 'telegram', fields: [
    { key: 'telegram_bot_enable', label: '启用 Telegram 绑定引导', type: 'boolean' }, { key: 'telegram_bot_token', label: '机器人令牌', type: 'password' },
    { key: 'telegram_webhook_url', label: 'Webhook Base URL' }, { key: 'telegram_discuss_link', label: '群组链接' },
  ] },
  { key: 'app', title: '客户端设置', icon: 'Laptop2', description: '桌面和 Android 客户端版本及下载地址。', fields: [
    { key: 'windows_version', label: 'Windows 版本' }, { key: 'windows_download_url', label: 'Windows 下载地址' },
    { key: 'macos_version', label: 'macOS 版本' }, { key: 'macos_download_url', label: 'macOS 下载地址' },
    { key: 'android_version', label: 'Android 版本' }, { key: 'android_download_url', label: 'Android 下载地址' },
  ] },
  { key: 'safe', title: '安全设置', icon: 'ShieldCheck', description: '邮箱验证、验证码、注册与登录限制。', fields: [
    { key: 'email_verify', label: '强制邮箱验证', type: 'boolean' }, { key: 'safe_mode_enable', label: '安全模式', type: 'boolean' },
    { key: 'secure_path', label: '后台路径', help: '至少 8 位，仅限字母、数字、下划线和短横线；修改后需要使用新地址。' },
    { key: 'email_whitelist_enable', label: '启用邮箱后缀白名单', type: 'boolean' }, { key: 'email_whitelist_suffix', label: '允许的邮箱后缀', type: 'lines' },
    { key: 'email_gmail_limit_enable', label: '禁止 Gmail 多别名', type: 'boolean' }, { key: 'captcha_enable', label: '启用人机验证', type: 'boolean' },
    { key: 'captcha_type', label: '验证码类型', type: 'select', options: [{ value: 'recaptcha', label: 'reCAPTCHA v2' }, { value: 'recaptcha-v3', label: 'reCAPTCHA v3' }, { value: 'turnstile', label: 'Cloudflare Turnstile' }] },
    { key: 'recaptcha_key', label: 'reCAPTCHA 密钥', type: 'password' }, { key: 'recaptcha_site_key', label: 'reCAPTCHA 站点密钥' },
    { key: 'recaptcha_v3_secret_key', label: 'reCAPTCHA v3 密钥', type: 'password' }, { key: 'recaptcha_v3_site_key', label: 'reCAPTCHA v3 站点密钥' },
    { key: 'recaptcha_v3_score_threshold', label: 'reCAPTCHA v3 分数阈值', type: 'number' }, { key: 'turnstile_secret_key', label: 'Turnstile 密钥', type: 'password' },
    { key: 'turnstile_site_key', label: 'Turnstile 站点密钥' }, { key: 'register_limit_by_ip_enable', label: '限制同 IP 注册', type: 'boolean' },
    { key: 'register_limit_count', label: '允许注册次数', type: 'number' }, { key: 'register_limit_expire', label: '注册限制时长（分钟）', type: 'number' },
    { key: 'password_limit_enable', label: '限制密码尝试', type: 'boolean' }, { key: 'password_limit_count', label: '允许尝试次数', type: 'number' }, { key: 'password_limit_expire', label: '账户锁定时长（分钟）', type: 'number' },
  ] },
  { key: 'subscribe_template', title: '订阅模板', icon: 'FileCode2', description: '各客户端的原始订阅配置模板。', wide: true, fields: [
    { key: 'subscribe_template_singbox', label: 'Sing-box 模板', type: 'textarea' }, { key: 'subscribe_template_clash', label: 'Clash 模板', type: 'textarea' },
    { key: 'subscribe_template_clashmeta', label: 'Clash Meta 模板', type: 'textarea' }, { key: 'subscribe_template_stash', label: 'Stash 模板', type: 'textarea' },
    { key: 'subscribe_template_surge', label: 'Surge 模板', type: 'textarea' }, { key: 'subscribe_template_surfboard', label: 'Surfboard 模板', type: 'textarea' },
  ] },
];
