import * as React from "react"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { ArrowLeft, BellRing, Copy, Gift, KeyRound, LoaderCircle, Mail, MessageSquareReply, Send, TicketCheck, Upload, UserRound, WalletCards, XCircle } from "lucide-react"
import { Link, useNavigate, useSearchParams } from "react-router-dom"
import { toast } from "sonner"
import { useLanguage, useSession } from "@/app/providers"
import { ConfirmDialog, DataTable, EmptyState, ErrorAlert, PageHeader, PageLoading, RichContent, StatCards, StatusBadge } from "@/components/common"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Field, Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { api } from "@/lib/api"
import { appAsset, defaultAvatar } from "@/lib/runtime"
import { bytes, copyText, formatDate, formatTime, money, statusText } from "@/lib/format"
import { formObject, normalizeCollection } from "@/lib/utils"

export function ProfilePage() {
  const { user, comm, refresh } = useSession(); const queryClient = useQueryClient(); const [name,setName] = React.useState(String(user?.name || "")); const [expire,setExpire] = React.useState(Number(user?.remind_expire) === 1); const [traffic,setTraffic] = React.useState(Number(user?.remind_traffic) === 1); const [busy,setBusy] = React.useState(""); const [preview,setPreview] = React.useState("")
  const giftQuery = useQuery({ queryKey:["gift-history"], queryFn:({signal}) => api.get<any>("/user/gift-card/history",{per_page:8},{signal}).then((value) => normalizeCollection<any>(value?.data || value)).catch(() => []) })
  React.useEffect(() => { setName(String(user?.name || "")); setExpire(Number(user?.remind_expire) === 1); setTraffic(Number(user?.remind_traffic) === 1) },[user])
  React.useEffect(() => () => { if (preview.startsWith("blob:")) URL.revokeObjectURL(preview) },[preview])
  const currency = comm?.currency_symbol || "¥"; const avatar = preview || user?.avatar || (user?.avatar_url && !String(user.avatar_url).includes("/gravatar/") ? user.avatar_url : defaultAvatar())
  async function run(key:string, task:()=>Promise<unknown>,message:string, reset?:HTMLFormElement) { setBusy(key); try { await task(); await refresh(); toast.success(message); reset?.reset() } catch(error) { toast.error(error instanceof Error ? error.message : "操作失败") } finally { setBusy("") } }
  async function upload(file?:File) { if (!file) return; if(file.size > 2*1024*1024) return toast.error("头像不能超过 2MB"); if(preview.startsWith("blob:")) URL.revokeObjectURL(preview); setPreview(URL.createObjectURL(file)); const data = new FormData(); data.append("avatar",file); await run("avatar",() => api.post("/user/avatar",data),"头像已更新"); setPreview("") }
  const giftRows = (giftQuery.data || []).map((item) => [item.code || "-",item.template_name || "-",formatTime(item.created_at)])
  return <div className="grid gap-5"><PageHeader title="账号设置" description="管理个人资料、安全设置、提醒和礼品卡。" /><ErrorAlert error={giftQuery.error} />
    <Card><CardHeader><CardDescription>{user?.email || "当前账号"}</CardDescription><CardTitle>账户信息</CardTitle></CardHeader><CardContent className="grid gap-6 lg:grid-cols-[180px_1fr]"><div className="grid justify-items-center gap-3"><Avatar className="size-28 border"><AvatarImage src={avatar} /><AvatarFallback className="text-2xl">{String(name || user?.email || "U").slice(0,1)}</AvatarFallback></Avatar><Label className="cursor-pointer"><Button asChild variant="outline" size="sm"><span>{busy === "avatar" ? <LoaderCircle className="animate-spin" /> : <Upload />}上传头像</span></Button><Input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={(event) => upload(event.target.files?.[0])} /></Label><small className="text-center text-muted-foreground">JPG/PNG/WebP/GIF，最大 2MB</small></div><div className="grid content-start gap-5"><form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); run("identity",() => api.post("/user/update",{name:name.trim()}),"资料已保存") }}><Field label="昵称"><Input value={name} onChange={(event) => setName(event.target.value)} maxLength={64} placeholder={user?.email?.split("@")[0]} /></Field><Button className="w-fit" disabled={busy === "identity"}>{busy === "identity" ? <LoaderCircle className="animate-spin" /> : <UserRound />}保存资料</Button></form><StatCards items={[{label:"余额",value:money(user?.balance,currency)},{label:"佣金余额",value:money(user?.commission_balance,currency)},{label:"注册时间",value:formatDate(user?.created_at)},{label:"UUID",value:<span className="text-sm">{user?.uuid || "-"}</span>}]} /></div></CardContent></Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>提醒设置</CardTitle><CardDescription>配置套餐到期与流量提醒。</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={(event) => {event.preventDefault();run("reminders",() => api.post("/user/update",{remind_expire:expire?1:0,remind_traffic:traffic?1:0}),"设置已保存")}}><Label className="rounded-lg border p-4"><Checkbox checked={expire} onCheckedChange={(value) => setExpire(value === true)} /><span><strong className="block">套餐到期提醒</strong><small className="text-muted-foreground">套餐即将到期时发送通知</small></span></Label><Label className="rounded-lg border p-4"><Checkbox checked={traffic} onCheckedChange={(value) => setTraffic(value === true)} /><span><strong className="block">流量耗尽提醒</strong><small className="text-muted-foreground">剩余流量不足时发送通知</small></span></Label><Button disabled={busy === "reminders"}>{busy === "reminders" ? <LoaderCircle className="animate-spin" /> : <BellRing />}保存设置</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>佣金划转</CardTitle><CardDescription>将可用佣金转入账户余额。</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={(event) => {event.preventDefault();const amount=Number(new FormData(event.currentTarget).get("amount")||0);run("transfer",() => api.post("/user/transfer",{transfer_amount:Math.round(amount*100)}),"划转成功",event.currentTarget)}}><Field label="划转金额"><Input name="amount" type="number" min="0.01" step="0.01" placeholder="10.00" required /></Field><Button disabled={busy === "transfer"}>{busy === "transfer" ? <LoaderCircle className="animate-spin" /> : <WalletCards />}转入余额</Button></form></CardContent></Card></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>修改密码</CardTitle><CardDescription>建议定期更新账户密码。</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={(event) => {event.preventDefault();run("password",() => api.post("/user/changePassword",formObject(event.currentTarget)),"密码已更新",event.currentTarget)}}><Field label="旧密码"><Input name="old_password" type="password" autoComplete="current-password" required /></Field><Field label="新密码"><Input name="new_password" type="password" autoComplete="new-password" minLength={8} required /></Field><Button disabled={busy === "password"}>{busy === "password" ? <LoaderCircle className="animate-spin" /> : <KeyRound />}更新密码</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>礼品卡兑换</CardTitle><CardDescription>输入有效兑换码领取权益。</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={(event) => {event.preventDefault();run("gift",async() => {await api.post("/user/gift-card/redeem",formObject(event.currentTarget));await queryClient.invalidateQueries({queryKey:["gift-history"]})},"兑换成功",event.currentTarget)}}><Field label="兑换码"><Input name="code" placeholder="输入兑换码" required /></Field><Button disabled={busy === "gift"}>{busy === "gift" ? <LoaderCircle className="animate-spin" /> : <Gift />}立即兑换</Button></form></CardContent></Card></div>
    <Card><CardHeader><CardTitle>兑换记录</CardTitle><CardDescription>最近兑换的礼品卡。</CardDescription></CardHeader><CardContent><DataTable headers={["兑换码","名称","兑换时间"]} rows={giftRows} empty="暂无兑换记录" /></CardContent></Card>
  </div>
}

export function NodesPage() {
  const query = useQuery({queryKey:["nodes"],queryFn:({signal}) => api.get<any>("/user/server/fetch",{}, {signal}).then((value) => normalizeCollection<any>(value?.data || value)).catch(() => [])})
  if(query.isLoading)return <PageLoading cards={2}/>
  const rows=(query.data||[]).map((node)=>[node.name||"-",node.type||"-",<StatusBadge ok={Boolean(node.is_online)}>{node.is_online?"在线":"离线"}</StatusBadge>,node.rate??"-",Array.isArray(node.tags)?node.tags.join(", "):node.tags||"-",formatTime(node.last_check_at)])
  return <div><PageHeader title="节点状态" description="查看可用节点、协议、倍率和检测时间。"/><ErrorAlert error={query.error}/><Card><CardContent><DataTable headers={["节点","协议","状态","倍率","标签","检测时间"]} rows={rows} empty="暂无可用节点"/></CardContent></Card></div>
}

export function TrafficPage() {
  const query=useQuery({queryKey:["traffic"],queryFn:({signal})=>api.get<any>("/user/stat/getTrafficLog",{}, {signal}).then((value)=>normalizeCollection<any>(value))})
  if(query.isLoading)return <PageLoading cards={2}/>
  const rows=(query.data||[]).map((item)=>[formatDate(item.record_at),bytes(item.u),bytes(item.d),bytes(Number(item.u||0)+Number(item.d||0)),item.server_rate??"-"])
  return <div><PageHeader title="流量统计" description="查看每日上传、下载和计费倍率。"/><ErrorAlert error={query.error}/><Card><CardContent><DataTable headers={["日期","上传","下载","总计","倍率"]} rows={rows} empty="暂无流量记录"/></CardContent></Card></div>
}

const ticketStatus:Record<number,string>={0:"处理中",1:"已关闭"}; const ticketLevel:Record<number,string>={0:"低",1:"中",2:"高"}
export function TicketsPage(){const[params]=useSearchParams();const id=params.get("id");return id?<TicketDetail id={id}/>:<TicketList/>}
function TicketList() {
  const queryClient = useQueryClient()
  const [busy, setBusy] = React.useState(false)
  const [level, setLevel] = React.useState("0")
  const query = useQuery({ queryKey: ["tickets"], queryFn: ({ signal }) => api.get<any>("/user/ticket/fetch", {}, { signal }).then((value) => normalizeCollection<any>(value)) })
  if (query.isLoading) return <PageLoading cards={2} />
  const rows = (query.data || []).map((ticket) => [<Link className="text-primary hover:underline" to={`/tickets?id=${ticket.id}`}>{ticket.subject}</Link>, ticketLevel[Number(ticket.level)] || "-", <StatusBadge ok={Number(ticket.status) === 0}>{statusText(ticket.status, ticketStatus)}</StatusBadge>, formatTime(ticket.updated_at || ticket.created_at)])
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const form = event.currentTarget
    setBusy(true)
    try {
      await api.post("/user/ticket/save", { ...formObject(form), level })
      form.reset()
      setLevel("0")
      await queryClient.invalidateQueries({ queryKey: ["tickets"] })
      toast.success("工单已提交")
    } catch (error) { toast.error(error instanceof Error ? error.message : "提交失败") }
    finally { setBusy(false) }
  }
  return <div className="grid gap-5"><PageHeader title="工单中心" description="提交问题并跟踪客服回复。" /><ErrorAlert error={query.error} /><div className="grid items-start gap-5 xl:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle>新建工单</CardTitle></CardHeader><CardContent><form className="grid gap-4" onSubmit={submit}><Field label="标题"><Input name="subject" required /></Field><Field label="等级"><Select value={level} onValueChange={setLevel}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="0">低</SelectItem><SelectItem value="1">中</SelectItem><SelectItem value="2">高</SelectItem></SelectContent></Select></Field><Field label="内容"><Textarea name="message" rows={6} required /></Field><Button disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : <Send />}提交工单</Button></form></CardContent></Card><Card><CardHeader><CardTitle>工单列表</CardTitle></CardHeader><CardContent><DataTable headers={["标题", "等级", "状态", "更新时间"]} rows={rows} empty="暂无工单" /></CardContent></Card></div></div>
}
function TicketDetail({id}:{id:string}){const navigate=useNavigate();const queryClient=useQueryClient();const[busy,setBusy]=React.useState(false);const[closeOpen,setCloseOpen]=React.useState(false);const query=useQuery({queryKey:["ticket",id],queryFn:({signal})=>api.get<any>("/user/ticket/fetch",{id},{signal})});if(query.isLoading)return <PageLoading cards={2}/>;const ticket=query.data||{};const messages=normalizeCollection<any>(ticket.message);async function reply(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{await api.post("/user/ticket/reply",{id,...formObject(event.currentTarget)});event.currentTarget.reset();await queryClient.invalidateQueries({queryKey:["ticket",id]});toast.success("回复已发送")}catch(error){toast.error(error instanceof Error?error.message:"发送失败")}finally{setBusy(false)}}async function close(){setBusy(true);try{await api.post("/user/ticket/close",{id});toast.success("工单已关闭");navigate("/tickets")}catch(error){toast.error(error instanceof Error?error.message:"关闭失败")}finally{setBusy(false);setCloseOpen(false)}}return <div className="grid gap-5"><Button variant="ghost" className="w-fit" onClick={()=>navigate("/tickets")}><ArrowLeft/>返回工单列表</Button><ErrorAlert error={query.error}/><PageHeader title={ticket.subject||"工单详情"} description={statusText(ticket.status,ticketStatus)} actions={<StatusBadge ok={Number(ticket.status)===0}>{statusText(ticket.status,ticketStatus)}</StatusBadge>}/><Card><CardContent className="grid gap-3">{messages.length?messages.map((message,index)=><article key={message.id||index} className={`max-w-[84%] rounded-xl border p-4 ${message.is_me?"ml-auto bg-primary/5":"bg-muted/35"}`}><RichContent html={message.message||""}/><time className="mt-2 block text-xs text-muted-foreground">{formatTime(message.created_at)}</time></article>):<EmptyState title="暂无回复"/>}</CardContent></Card>{Number(ticket.status)===0?<Card><CardHeader><CardTitle>回复工单</CardTitle></CardHeader><CardContent><form className="grid gap-4" onSubmit={reply}><Textarea name="message" rows={5} required/><div className="flex gap-2"><Button disabled={busy}>{busy?<LoaderCircle className="animate-spin"/>:<MessageSquareReply/>}发送回复</Button><Button type="button" variant="outline" onClick={()=>setCloseOpen(true)}><XCircle/>关闭工单</Button></div></form></CardContent></Card>:null}<ConfirmDialog open={closeOpen} onOpenChange={setCloseOpen} title="关闭该工单？" description="关闭后将无法继续回复。" confirmLabel="确认关闭" destructive busy={busy} onConfirm={close}/></div>}

export function InvitePage(){const{comm}=useSession();const queryClient=useQueryClient();const[busy,setBusy]=React.useState(false);const query=useQuery({queryKey:["invite"],queryFn:async({signal})=>{const[invite,details]=await Promise.all([api.get<any>("/user/invite/fetch",{}, {signal}),api.get<any>("/user/invite/details",{current:1,page_size:10},{signal}).catch(()=>({data:[]}))]);return{invite,details:normalizeCollection<any>(details?.data||details)}}});if(query.isLoading)return <PageLoading cards={4}/>;const invite=query.data?.invite||{};const currency=comm?.currency_symbol||"¥";async function create(){setBusy(true);try{await api.get("/user/invite/save");await queryClient.invalidateQueries({queryKey:["invite"]});toast.success("邀请码已生成")}catch(error){toast.error(error instanceof Error?error.message:"生成失败")}finally{setBusy(false)}}async function copy(code:string){await copyText(`${location.origin}/#/register?invite_code=${encodeURIComponent(code)}`);toast.success("邀请链接已复制")}const codes=normalizeCollection<any>(invite.codes);const codeRows=codes.map((item)=>[item.code,item.pv??0,formatTime(item.created_at),<Button variant="link" size="sm" onClick={()=>copy(item.code)}><Copy/>复制链接</Button>]);const detailRows=(query.data?.details||[]).map((item)=>[item.trade_no,money(item.order_amount,currency),money(item.get_amount,currency),formatTime(item.created_at)]);return <div className="grid gap-5"><PageHeader title="邀请好友" description="生成邀请链接并查看佣金明细。" actions={<Button disabled={busy} onClick={create}>{busy?<LoaderCircle className="animate-spin"/>:<Gift/>}生成邀请码</Button>}/><ErrorAlert error={query.error}/><StatCards items={[{label:"注册用户",value:invite.stat?.[0]??0},{label:"累计佣金",value:money(invite.stat?.[1],currency)},{label:"确认中",value:money(invite.stat?.[2],currency)},{label:"佣金比例",value:`${invite.stat?.[3]??0}%`} ]}/><Card><CardHeader><CardTitle>邀请码</CardTitle><CardDescription>分享链接邀请好友注册。</CardDescription></CardHeader><CardContent><DataTable headers={["邀请码","访问量","创建时间","操作"]} rows={codeRows} empty="暂无邀请码"/></CardContent></Card><Card><CardHeader><CardTitle>佣金明细</CardTitle></CardHeader><CardContent><DataTable headers={["订单号","订单金额","获得佣金","时间"]} rows={detailRows} empty="暂无佣金明细"/></CardContent></Card></div>}

export function KnowledgePage(){const[params]=useSearchParams();const navigate=useNavigate();const{language}=useLanguage();const id=params.get("id");const query=useQuery({queryKey:["knowledge",language,id],queryFn:({signal})=>api.get<any>("/user/knowledge/fetch",id?{id,language}:{language},{signal})});if(query.isLoading)return <PageLoading cards={3}/>;if(id){const article=query.data||{};return <div className="grid gap-5"><Button variant="ghost" className="w-fit" onClick={()=>navigate("/knowledge")}><ArrowLeft/>返回知识库</Button><ErrorAlert error={query.error}/><Card><CardHeader><CardDescription>{formatTime(article.updated_at)}</CardDescription><CardTitle className="text-2xl">{article.title||"知识库"}</CardTitle></CardHeader><CardContent><RichContent html={article.body||""}/></CardContent></Card></div>}const grouped=query.data&&typeof query.data==="object"?query.data:{};const entries=Object.entries(grouped);return <div className="grid gap-5"><PageHeader title="使用教程" description="浏览常见问题与使用指南。"/><ErrorAlert error={query.error}/>{entries.length?entries.map(([category,articles])=><Card key={category}><CardHeader><CardTitle>{category||"默认分类"}</CardTitle></CardHeader><CardContent className="grid gap-2">{normalizeCollection<any>(articles).map((article)=><Link key={article.id} to={`/knowledge?id=${article.id}`} className="flex items-center justify-between gap-4 rounded-lg border p-4 transition hover:bg-accent"><div><strong>{article.title}</strong><p className="mt-1 text-xs text-muted-foreground">{formatTime(article.updated_at)}</p></div><ArrowLeft className="rotate-180 text-muted-foreground"/></Link>)}</CardContent></Card>):<EmptyState title="暂无知识库文章"/>}</div>}
