<script setup>
import { onMounted, reactive, ref } from 'vue';
import { getEnvelope } from '../services/http';
const rows=ref([]),loading=ref(true),detail=ref(null);const filters=reactive({keyword:'',action:'',admin_id:''});const page=reactive({current:1,size:20,total:0,last:1});const toast=reactive({text:'',type:'error'});
function time(v){return new Date((typeof v==='number'?v*1000:v)).toLocaleString('zh-CN',{hour12:false})}function result(r){try{return JSON.parse(r.request_data||'{}')._response_status||200}catch{return 200}}function payload(r){try{const x=JSON.parse(r.request_data||'{}');delete x._response_status;return JSON.stringify(x,null,2)}catch{return r.request_data||'{}'}}
async function load(reset=false){if(reset)page.current=1;loading.value=true;try{const d=await getEnvelope('/system/getAuditLog',{...filters,current:page.current,page_size:page.size});rows.value=d.data||[];page.total=Number(d.total||0);page.last=Math.max(1,Math.ceil(page.total/page.size))}catch(e){toast.text=e.message}finally{loading.value=false}}
onMounted(()=>load());
</script>
<template><section class="page-stack"><div class="page-heading"><h1>操作审计</h1><p>追踪管理员操作、来源 IP、请求结果和脱敏后的参数。</p></div><div class="panel audit-toolbar"><label class="filter-input"><span>关键字</span><input v-model.trim="filters.keyword" placeholder="接口或参数" @keyup.enter="load(true)"/></label><label class="filter-input"><span>操作标识</span><input v-model.trim="filters.action" placeholder="例如 user.update" @keyup.enter="load(true)"/></label><label class="filter-input"><span>管理员 ID</span><input v-model="filters.admin_id" type="number" min="1" @keyup.enter="load(true)"/></label><button class="btn btn-primary" @click="load(true)">查询</button></div><section class="panel table-wrap audit-table"><table><thead><tr><th>时间</th><th>管理员</th><th>操作</th><th>来源 IP</th><th>请求</th><th>结果</th><th class="right">详情</th></tr></thead><tbody><tr v-if="loading"><td colspan="7" class="empty">正在读取审计记录…</td></tr><tr v-else-if="!rows.length"><td colspan="7" class="empty">暂无符合条件的记录</td></tr><tr v-for="r in rows" :key="r.id"><td>{{time(r.created_at)}}</td><td><strong>{{r.admin?.email||`管理员 #${r.admin_id}`}}</strong></td><td><code>{{r.action}}</code></td><td><code>{{r.ip||'—'}}</code></td><td><span class="audit-method">{{r.method}}</span><small>{{r.uri}}</small></td><td><span class="status-pill" :class="{off:result(r)>=400}">{{result(r)}}</span></td><td class="right"><button class="btn btn-ghost btn-sm" @click="detail=r">查看</button></td></tr></tbody></table></section><div class="pagination"><span>共 {{page.total}} 条</span><button class="btn btn-ghost btn-sm" :disabled="page.current<=1||loading" @click="page.current--;load()">上一页</button><span>{{page.current}} / {{page.last}}</span><button class="btn btn-ghost btn-sm" :disabled="page.current>=page.last||loading" @click="page.current++;load()">下一页</button></div><div v-if="detail" class="modal-backdrop" @click.self="detail=null"><section class="modal-card audit-detail"><div class="panel-head"><div><h2>{{detail.action}}</h2><p>{{detail.method}} · {{detail.uri}}</p></div><button class="btn btn-ghost" @click="detail=null">关闭</button></div><div class="detail-summary"><span>管理员<strong>{{detail.admin?.email||detail.admin_id}}</strong></span><span>来源 IP<strong>{{detail.ip||'—'}}</strong></span><span>响应状态<strong>{{result(detail)}}</strong></span><span>时间<strong>{{time(detail.created_at)}}</strong></span></div><h3>脱敏请求参数</h3><pre class="audit-payload">{{payload(detail)}}</pre></section></div><div v-if="toast.text" class="toast error">{{toast.text}}</div></section></template>
