<script setup>
import { onMounted, reactive, ref } from 'vue';
import { get, post } from '../services/http';
import ToggleSwitch from '../components/ToggleSwitch.vue';
const rows=ref([]),loading=ref(true),creating=ref(false),saving=ref(false);const form=reactive({enabled:false,time:'03:30',retention:14});const toast=reactive({text:'',type:'success'});
function notify(t,type='success'){toast.text=t;toast.type=type;clearTimeout(notify.x);notify.x=setTimeout(()=>toast.text='',3500)}function size(v){if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;return`${(v/1048576).toFixed(1)} MB`}function time(v){return new Date(Number(v)*1000).toLocaleString('zh-CN',{hour12:false})}
async function load(){loading.value=true;try{const d=await get('/backup/fetch');rows.value=d.files||[];Object.assign(form,d.settings||{})}catch(e){notify(e.message,'error')}finally{loading.value=false}}
async function create(){creating.value=true;try{await post('/backup/create');notify('数据库备份已完成');await load()}catch(e){notify(e.message,'error')}finally{creating.value=false}}
async function save(){saving.value=true;try{await post('/backup/settings',form);notify('自动备份设置已保存')}catch(e){notify(e.message,'error')}finally{saving.value=false}}
onMounted(load);
</script>
<template><section class="page-stack"><div class="page-heading page-heading-row"><div><h1>备份管理</h1><p>创建数据库压缩备份，核对文件大小与 SHA-256 完整性。</p></div><button class="btn btn-primary" :disabled="creating" @click="create">{{creating?'备份执行中…':'立即创建备份'}}</button></div><section class="panel backup-settings"><div><h2>自动备份</h2><p>定时生成本地数据库压缩备份，并按保留天数自动轮换。</p></div><ToggleSwitch v-model="form.enabled" on-label="已开启" off-label="已关闭"/><label class="field"><span>执行时间</span><input v-model="form.time" type="time"/></label><label class="field"><span>保留天数</span><input v-model.number="form.retention" type="number" min="1" max="365"/></label><button class="btn btn-ghost" :disabled="saving" @click="save">{{saving?'保存中…':'保存计划'}}</button></section><section class="panel table-wrap"><table><thead><tr><th>备份文件</th><th>生成时间</th><th>大小</th><th>SHA-256 校验值</th><th>状态</th></tr></thead><tbody><tr v-if="loading"><td colspan="5" class="empty">正在读取备份…</td></tr><tr v-else-if="!rows.length"><td colspan="5" class="empty">暂无备份文件</td></tr><tr v-for="r in rows" :key="r.name"><td><strong>{{r.name}}</strong></td><td>{{time(r.created_at)}}</td><td>{{size(r.size)}}</td><td><code class="backup-hash">{{r.sha256}}</code></td><td><span class="status-pill">校验完成</span></td></tr></tbody></table></section><div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div></section></template>
