<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import ToggleSwitch from '../components/ToggleSwitch.vue';
import { get, post } from '../services/http';

const rows = ref([]), loading = ref(true), saving = ref(false), showForm = ref(false), stockPlan = ref(null), stockText = ref(''), stockPackage = ref('');
const toast = reactive({ text: '', type: '' });
const form = reactive({ id: null, name: '', content: '', show: true, sell: true, prices: { onetime: 0 }, product_config: { delivery_type: 'text', packages: [{ id: 'default', name: '标准版', price: 0 }] } });
const selling = computed(() => rows.value.filter((row) => row.show && row.sell));
function notify(text, type = '') { toast.text = text; toast.type = type; clearTimeout(notify.timer); notify.timer = setTimeout(() => { toast.text = ''; }, 2600); }
async function load() { loading.value = true; try { const data = await get('/digital-products/fetch'); rows.value = Array.isArray(data) ? data : []; } catch (e) { notify(e.message, 'error'); } finally { loading.value = false; } }
function open(row = null) { Object.assign(form, { id: row?.id || null, name: row?.name || '', content: row?.content || '', show: row?.show ?? true, sell: row?.sell ?? true, prices: { ...(row?.prices || {}), onetime: row?.prices?.onetime || 0 }, product_config: { delivery_type: row?.product_config?.delivery_type || 'text', packages: row?.product_config?.packages?.length ? row.product_config.packages.map((item) => ({ ...item })) : [{ id: 'default', name: '标准版', price: 0 }] } }); showForm.value = true; }
async function save() { const prices = Object.fromEntries(Object.entries(form.prices).filter(([, value]) => Number(value) > 0)); if (!form.name.trim()) return notify('请输入商品名称', 'error'); if (!Object.keys(prices).length) return notify('请设置销售价格', 'error'); saving.value = true; try { await post('/digital-products/save', { ...form, prices }); notify(form.id ? '商品已更新' : '商品已创建'); showForm.value = false; await load(); } catch (e) { notify(e.message, 'error'); } finally { saving.value = false; } }
async function importStock() { if (!stockPlan.value || !stockText.value.trim()) return notify('请选择商品并填写库存内容', 'error'); try { const result = await post('/digital-products/stock/import', { plan_id: stockPlan.value.id, package_id: stockPackage.value || null, content: stockText.value }); notify(`已导入 ${result.imported || 0} 条库存`); stockText.value = ''; stockPackage.value = ''; stockPlan.value = null; await load(); } catch (e) { notify(e.message, 'error'); } }
function addPackage() { form.product_config.packages.push({ id: `package-${Date.now()}`, name: '新套餐', price: 0 }); }
function removePackage(index) { if (form.product_config.packages.length > 1) form.product_config.packages.splice(index, 1); }
onMounted(load);
</script>
<template>
  <section class="page-stack forwarding-plans-page">
    <div class="page-heading page-heading-row"><div><h1>数字商品</h1><p>销售卡密、授权码、账号或下载链接，支付完成后自动从库存发货。</p></div><button class="btn btn-primary" @click="open()"><AppIcon name="Plus" :size="16" />新建商品</button></div>
    <div class="stat-grid"><article class="stat-card"><span>商品数量</span><strong>{{ rows.length }}</strong></article><article class="stat-card"><span>销售中</span><strong>{{ selling.length }}</strong></article><article class="stat-card"><span>可售库存</span><strong>{{ rows.reduce((n, r) => n + Number(r.stock_count || 0), 0) }}</strong></article><article class="stat-card"><span>已交付</span><strong>{{ rows.reduce((n, r) => n + Number(r.sold_count || 0), 0) }}</strong></article></div>
    <div v-if="loading" class="panel settings-loading">正在加载数字商品…</div><div v-else-if="!rows.length" class="panel settings-loading">暂无数字商品，点击右上角新建</div>
    <div v-else class="forwarding-plan-grid"><article v-for="row in rows" :key="row.id" class="panel forwarding-plan-card"><div class="forwarding-plan-head"><div><span class="plan-group">{{ row.product_config?.delivery_type || 'text' }}</span><h2>{{ row.name }}</h2><small>#{{ row.id }} · {{ row.content || '未填写商品说明' }}</small></div><span class="status-pill" :class="{ off: !row.sell }">{{ row.sell ? '销售中' : '已停售' }}</span></div><div class="forwarding-plan-rights"><span><small>可售库存</small><strong>{{ row.stock_count || 0 }}</strong></span><span><small>已交付</small><strong>{{ row.sold_count || 0 }}</strong></span><span><small>一次性价格</small><strong>¥ {{ Number(row.prices?.onetime || 0).toFixed(2) }}</strong></span></div><div class="plan-actions"><button class="btn btn-primary btn-sm" @click="stockPlan = row">导入库存</button><button class="btn btn-ghost btn-sm" @click="open(row)">编辑</button></div></article></div>
    <div v-if="stockPlan" class="modal-backdrop" @click.self="stockPlan = null"><section class="modal-card"><div class="panel-head"><div><h2>导入库存 · {{ stockPlan.name }}</h2><p>每行一条交付内容，支持卡密、授权码、账号或链接。</p></div><button class="btn btn-ghost" @click="stockPlan = null">关闭</button></div><label class="field"><span>归属套餐</span><select v-model="stockPackage"><option value="">通用库存</option><option v-for="item in (stockPlan.product_config?.packages || [])" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><textarea v-model="stockText" rows="14" placeholder="CODE-001\nCODE-002\nCODE-003" /><div class="modal-actions"><button class="btn btn-primary" @click="importStock">导入库存</button></div></section></div>
    <div v-if="showForm" class="modal-backdrop" @click.self="showForm = false"><section class="modal-card forwarding-plan-modal"><div class="panel-head"><div><h2>{{ form.id ? '编辑数字商品' : '新建数字商品' }}</h2><p>价格单位为元；库存需在商品创建后单独导入。</p></div><button class="btn btn-ghost" @click="showForm = false">关闭</button></div><div class="smart-form"><label class="field field-wide"><span>商品名称 *</span><input v-model.trim="form.name" maxlength="100" placeholder="例如：高级账号授权码" /></label><label class="field field-wide"><span>商品说明</span><textarea v-model="form.content" rows="3" placeholder="展示给购买用户的说明" /></label><label class="field"><span>交付类型</span><select v-model="form.product_config.delivery_type"><option value="text">文本</option><option value="code">卡密</option><option value="link">下载链接</option><option value="account">账号信息</option></select></label><label class="field"><span>展示状态</span><ToggleSwitch v-model="form.show" on-label="已展示" off-label="已隐藏" /></label><label class="field"><span>购买状态</span><ToggleSwitch v-model="form.sell" on-label="销售中" off-label="已停售" /></label></div><h3 class="plan-form-title">销售套餐 *</h3><div class="digital-package-editor"><div v-for="(item, index) in form.product_config.packages" :key="item.id" class="digital-package-row"><input v-model.trim="item.id" placeholder="套餐标识" /><input v-model.trim="item.name" placeholder="套餐名称" /><input v-model.number="item.price" type="number" min="0" step="0.01" placeholder="价格（元）" /><button class="btn btn-ghost btn-sm" @click="removePackage(index)">移除</button></div><button class="btn btn-ghost btn-sm" @click="addPackage">＋添加套餐</button></div><div class="modal-actions"><button class="btn btn-ghost" @click="showForm = false">取消</button><button class="btn btn-primary" :disabled="saving" @click="save">{{ saving ? '保存中…' : '保存商品' }}</button></div></section></div><div v-if="toast.text" class="toast" :class="{ error: toast.type === 'error' }">{{ toast.text }}</div>
  </section>
</template>
