<script setup>
import { computed, onMounted, ref } from 'vue';
import { get, post, request } from '../services/http';

const products = ref([]), selectedId = ref(''), items = ref([]), loading = ref(false), importing = ref(false), stockText = ref(''), stockPackage = ref('');
const filters = ref({ keyword: '', status: '' });
const page = ref({ current: 1, size: 20, total: 0, last: 1 });
const selectedProduct = computed(() => products.value.find((item) => String(item.id) === String(selectedId.value)) || null);
const available = computed(() => Number(selectedProduct.value?.stock_count || 0));
const sold = computed(() => Number(selectedProduct.value?.sold_count || 0));
function packageName(id) { return selectedProduct.value?.product_config?.packages?.find((item) => String(item.id) === String(id))?.name || '通用库存'; }
async function loadProducts() { const data = await get('/digital-products/fetch'); products.value = Array.isArray(data) ? data : []; if (!selectedId.value && products.value[0]) selectedId.value = products.value[0].id; }
async function loadStock(reset = false) { if (!selectedId.value) { items.value = []; return; } if (reset) page.value.current = 1; loading.value = true; try { const params = new URLSearchParams({ plan_id: selectedId.value, current: page.value.current, pageSize: page.value.size }); if (filters.value.keyword) params.set('keyword', filters.value.keyword); if (filters.value.status) params.set('status', filters.value.status); const data = await request(`/digital-products/stock?${params}`); const source = data?.data ?? data; items.value = source?.items || source?.data || (Array.isArray(source) ? source : []); page.value.total = Number(source?.total || items.value.length); page.value.last = Number(source?.last_page || Math.max(1, Math.ceil(page.value.total / page.value.size))); } finally { loading.value = false; } }
async function importStock() { if (!selectedProduct.value || !stockText.value.trim()) return; importing.value = true; try { await post('/digital-products/stock/import', { plan_id: selectedProduct.value.id, package_id: stockPackage.value || null, content: stockText.value }); stockText.value = ''; stockPackage.value = ''; await loadStock(); await loadProducts(); } finally { importing.value = false; } }
async function remove(item) { if (item.status !== 'available' || !window.confirm('确定删除这条未售库存吗？')) return; await post('/digital-products/stock/drop', { id: item.id }); await loadStock(); await loadProducts(); }
onMounted(async () => { await loadProducts(); await loadStock(); });
</script>
<template>
  <section class="page-stack">
    <div class="page-heading"><div><h1>库存管理</h1><p>统一管理数字商品库存、套餐归属和交付状态。</p></div></div>
    <div class="panel digital-inventory-toolbar"><label class="field"><span>选择商品</span><select v-model="selectedId" @change="loadStock(true)"><option value="">请选择数字商品</option><option v-for="product in products" :key="product.id" :value="product.id">{{ product.name }}</option></select></label><label v-if="selectedProduct" class="field"><span>导入到套餐</span><select v-model="stockPackage"><option value="">通用库存</option><option v-for="item in (selectedProduct.product_config?.packages || [])" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><button class="btn btn-primary" :disabled="importing || !selectedProduct || !stockText.trim()" @click="importStock">{{ importing ? '导入中…' : '导入库存' }}</button></div>
    <div v-if="selectedProduct" class="stat-grid"><article class="stat-card"><span>库存总数</span><strong>{{ available + sold }}</strong></article><article class="stat-card"><span>可交付</span><strong>{{ available }}</strong></article><article class="stat-card"><span>已交付</span><strong>{{ sold }}</strong></article></div>
    <div class="panel digital-inventory-import"><textarea v-model="stockText" rows="4" placeholder="每行一条库存内容，例如：CODE-001&#10;CODE-002" /></div>
    <div class="panel digital-inventory-table"><div class="panel-head"><div><h2>{{ selectedProduct?.name || '库存记录' }}</h2><p>已售库存仅保留记录，不允许删除。</p></div><span>{{ page.total }} 条记录</span></div><div class="digital-inventory-filters"><input v-model.trim="filters.keyword" placeholder="搜索库存内容" @keyup.enter="loadStock(true)" /><select v-model="filters.status" @change="loadStock(true)"><option value="">全部状态</option><option value="available">未交付</option><option value="sold">已交付</option></select><button class="btn btn-ghost btn-sm" @click="loadStock(true)">查询</button></div><div v-if="loading" class="settings-loading">正在加载库存…</div><div v-else-if="!items.length" class="settings-loading">暂无库存记录</div><div v-else class="digital-stock-list"><div v-for="item in items" :key="item.id" class="digital-stock-row"><div><strong>{{ item.content }}</strong><small>{{ packageName(item.package_id) }} · {{ item.status === 'available' ? '未交付' : '已交付' }}</small></div><button v-if="item.status === 'available'" class="btn btn-danger btn-sm" @click="remove(item)">删除</button></div></div><div v-if="page.last > 1" class="modal-actions"><button class="btn btn-ghost btn-sm" :disabled="page.current <= 1" @click="page.current--; loadStock()">上一页</button><span>{{ page.current }} / {{ page.last }}</span><button class="btn btn-ghost btn-sm" :disabled="page.current >= page.last" @click="page.current++; loadStock()">下一页</button></div></div>
  </section>
</template>
