<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import AppIcon from '../components/AppIcon.vue';
import ToggleSwitch from '../components/ToggleSwitch.vue';
import { get, post } from '../services/http';
import { confirmAction } from '../services/confirm';

const route = useRoute(), loading = ref(false), saving = ref(false), rows = ref([]), options = reactive({ nodes: [], tunnels: [], limits: [], users: [] });
const summary = reactive({ counts: {}, online_nodes: 0, traffic: 0 }), keyword = ref(''), showForm = ref(false), toast = reactive({ text: '', type: '' });
const page = reactive({ current: 1, last: 1, total: 0 }), form = reactive({});
const resource = computed(() => route.params.resource || 'dashboard');
const configs = {
  forwards:{title:'转发规则',desc:'管理 TCP/UDP 入口端口、目标地址、调度策略和所属用户。',icon:'Shuffle',columns:['name','user_id','tunnel_id','in_port','remote_addr','traffic','enabled'],defaults:{name:'',user_id:'',tunnel_id:'',in_port:'',out_port:'',remote_addr:'',strategy:'fifo',interface_name:'',sort:0,enabled:true},fields:[['name','名称','text'],['user_id','所属用户','users'],['tunnel_id','所属隧道','tunnels'],['in_port','入口端口','number'],['out_port','出口端口','number'],['remote_addr','目标地址','textarea'],['strategy','调度策略','strategy'],['interface_name','网卡名称','text'],['sort','排序','number'],['enabled','启用状态','switch']]},
  tunnels:{title:'隧道管理',desc:'配置入口、出口节点，转发协议、计费方向和流量倍率。',icon:'Waypoints',columns:['name','nodes','type','protocol','billing_mode','traffic_ratio','enabled'],defaults:{name:'',in_node_id:'',out_node_id:'',in_ip:'',out_ip:'',type:1,protocol:'tls',billing_mode:2,traffic_ratio:1,tcp_listen_addr:'[::]',udp_listen_addr:'[::]',interface_name:'',enabled:true},fields:[['name','隧道名称','text'],['in_node_id','入口节点','nodes'],['out_node_id','出口节点','nodes'],['in_ip','入口 IP','text'],['out_ip','出口 IP','text'],['type','转发模式','type'],['protocol','传输协议','protocol'],['billing_mode','计费方式','billing'],['traffic_ratio','流量倍率','number'],['tcp_listen_addr','TCP 监听地址','text'],['udp_listen_addr','UDP 监听地址','text'],['interface_name','网卡名称','text'],['enabled','启用状态','switch']]},
  nodes:{title:'转发节点',desc:'管理转发节点凭据、端口范围、协议能力和心跳状态。',icon:'Network',columns:['name','server_ip','ports','protocols','version','online','enabled'],defaults:{name:'',secret:'',ip:'',server_ip:'',port_start:10000,port_end:60000,version:'',allow_http:false,allow_tls:true,allow_socks:false,enabled:true},fields:[['name','节点名称','text'],['server_ip','服务地址','text'],['ip','附加 IP','textarea'],['secret','节点密钥','password'],['port_start','起始端口','number'],['port_end','结束端口','number'],['version','版本','text'],['allow_http','允许 HTTP','switch'],['allow_tls','允许 TLS','switch'],['allow_socks','允许 SOCKS','switch'],['enabled','启用状态','switch']]},
  limits:{title:'限速策略',desc:'按隧道创建可复用的带宽限制，并在用户授权中分配。',icon:'Gauge',columns:['name','tunnel_id','speed_mbps','enabled'],defaults:{name:'',tunnel_id:'',speed_mbps:100,enabled:true},fields:[['name','策略名称','text'],['tunnel_id','所属隧道','tunnels'],['speed_mbps','速度（Mbps）','number'],['enabled','启用状态','switch']]},
  access:{title:'用户授权',desc:'直接关联 Plus 用户，配置可用隧道、转发数量、流量和有效期。',icon:'ShieldCheck',columns:['user_id','tunnel_id','speed_limit_id','forward_limit','traffic_limit','expires_at','enabled'],defaults:{user_id:'',tunnel_id:'',speed_limit_id:null,forward_limit:1,traffic_limit:0,reset_at:null,expires_at:null,enabled:true},fields:[['user_id','Plus 用户','users'],['tunnel_id','授权隧道','tunnels'],['speed_limit_id','限速策略','limits'],['forward_limit','转发数量','number'],['traffic_limit','流量额度（字节，0 不限制）','number'],['reset_at','下次重置时间戳','number'],['expires_at','到期时间戳','number'],['enabled','授权状态','switch']]},
};
const config = computed(() => configs[resource.value]);
const nodeMap = computed(()=>Object.fromEntries(options.nodes.map(x=>[x.id,x.name]))), tunnelMap = computed(()=>Object.fromEntries(options.tunnels.map(x=>[x.id,x.name]))), userMap = computed(()=>Object.fromEntries(options.users.map(x=>[x.id,x.email]))), limitMap = computed(()=>Object.fromEntries(options.limits.map(x=>[x.id,x.name])));
function notify(text,type=''){toast.text=text;toast.type=type;setTimeout(()=>toast.text='',2600)}
function bytes(v){v=Number(v||0);if(!v)return '0 B';const u=['B','KB','MB','GB','TB'],i=Math.min(u.length-1,Math.floor(Math.log(v)/Math.log(1024)));return `${(v/1024**i).toFixed(i?1:0)} ${u[i]}`}
function label(row,key){if(key==='user_id')return userMap.value[row.user_id]||`用户 #${row.user_id}`;if(key==='tunnel_id')return tunnelMap.value[row.tunnel_id]||`隧道 #${row.tunnel_id}`;if(key==='speed_limit_id')return row.speed_limit_id?(limitMap.value[row.speed_limit_id]||`策略 #${row.speed_limit_id}`):'不限速';if(key==='nodes')return `${nodeMap.value[row.in_node_id]||'#'+row.in_node_id} → ${nodeMap.value[row.out_node_id]||'#'+row.out_node_id}`;if(key==='ports')return `${row.port_start}–${row.port_end}`;if(key==='protocols')return [['HTTP',row.allow_http],['TLS',row.allow_tls],['SOCKS',row.allow_socks]].filter(x=>x[1]).map(x=>x[0]).join(' / ')||'—';if(key==='online')return Number(row.last_seen_at)>=Date.now()/1000-180?'在线':'离线';if(key==='type')return Number(row.type)===1?'端口转发':'隧道转发';if(key==='billing_mode')return Number(row.billing_mode)===1?'单向':'双向';if(key==='traffic')return bytes(Number(row.upload_bytes)+Number(row.download_bytes));if(key==='traffic_limit')return Number(row.traffic_limit)?bytes(row.traffic_limit):'不限';if(key==='enabled')return row.enabled?'已启用':'已停用';return row[key]??'—'}
function columnName(k){return {name:'名称',user_id:'用户',tunnel_id:'隧道',in_port:'入口端口',remote_addr:'目标地址',traffic:'累计流量',enabled:'状态',nodes:'节点链路',type:'模式',protocol:'协议',billing_mode:'计费',traffic_ratio:'倍率',server_ip:'服务地址',ports:'端口范围',protocols:'协议能力',version:'版本',online:'心跳',speed_mbps:'速度',speed_limit_id:'限速',forward_limit:'转发数',traffic_limit:'流量额度',expires_at:'到期时间'}[k]||k}
async function loadOptions(){Object.assign(options,await get('/forwarding/options'))}
async function loadSummary(){Object.assign(summary,await get('/forwarding/summary'))}
async function load(){if(resource.value==='dashboard'){loading.value=true;try{await Promise.all([loadSummary(),loadOptions()])}finally{loading.value=false}return}loading.value=true;try{const d=await get(`/forwarding/${resource.value}`,{keyword:keyword.value,page:page.current,page_size:30});rows.value=d.data||[];page.total=d.total||0;page.last=d.last_page||1;await loadOptions()}catch(e){notify(e.message,'error')}finally{loading.value=false}}
function open(row=null){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,config.value.defaults,row||{});showForm.value=true}
async function save(){saving.value=true;try{await post(`/forwarding/${resource.value}/save`,{...form});notify(form.id?'配置已更新':'配置已创建');showForm.value=false;await load()}catch(e){notify(e.message,'error')}finally{saving.value=false}}
async function remove(row){if(!await confirmAction({title:'删除配置',message:`确定删除「${row.name||'#'+row.id}」？关联数据可能同时失效。`,danger:true,confirmText:'确认删除'}))return;try{await post(`/forwarding/${resource.value}/drop`,{id:row.id});notify('已删除');await load()}catch(e){notify(e.message,'error')}}
function choices(type){if(['nodes','tunnels','limits','users'].includes(type))return options[type];return []}
function optionText(type,o){return type==='users'?o.email:type==='limits'?`${o.name} · ${o.speed_mbps} Mbps`:type==='nodes'?`${o.name} · ${o.server_ip}`:o.name}
watch(()=>route.params.resource,()=>{page.current=1;keyword.value='';load()});onMounted(load);
</script>

<template><section class="page-stack flux-page">
  <div class="page-heading page-heading-row"><div><h1>{{resource==='dashboard'?'转发概览':config?.title}}</h1><p>{{resource==='dashboard'?'集中查看转发服务、节点心跳、隧道授权与流量运行情况。':config?.desc}}</p></div><button v-if="resource!=='dashboard'" class="btn btn-primary" @click="open()"><AppIcon name="Plus" :size="16"/>新建{{config?.title.replace('管理','').replace('规则','')}}</button></div>
  <template v-if="resource==='dashboard'"><div class="stat-grid flux-stats"><article class="stat-card"><span>转发规则</span><strong>{{summary.counts.forwards||0}}</strong></article><article class="stat-card"><span>隧道</span><strong>{{summary.counts.tunnels||0}}</strong></article><article class="stat-card"><span>在线节点</span><strong>{{summary.online_nodes}} / {{summary.counts.nodes||0}}</strong></article><article class="stat-card"><span>累计流量</span><strong>{{bytes(summary.traffic)}}</strong></article></div><div class="flux-module-grid"><RouterLink v-for="item in [{p:'forwards',i:'Shuffle',t:'转发规则',d:'入口端口与目标调度'},{p:'tunnels',i:'Waypoints',t:'隧道管理',d:'入口和出口链路编排'},{p:'nodes',i:'Network',t:'转发节点',d:'Agent 状态与协议能力'},{p:'limits',i:'Gauge',t:'限速策略',d:'可复用的带宽控制'},{p:'access',i:'ShieldCheck',t:'用户授权',d:'用户配额与有效期'}]" :key="item.p" class="panel flux-module" :to="`/forwarding/${item.p}`"><span><AppIcon :name="item.i" :size="21"/></span><div><h2>{{item.t}}</h2><p>{{item.d}}</p></div><b>{{summary.counts[item.p]||0}}</b><AppIcon name="ChevronRight" :size="18"/></RouterLink></div><div class="panel flux-guide"><AppIcon name="Info" :size="19"/><div><strong>原生集成模式</strong><p>转发数据与 Plus 用户、后台权限和审计体系统一；节点使用独立密钥通信，不再需要第二套管理员账号。</p></div></div></template>
  <template v-else><div class="flux-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" placeholder="输入名称、地址或目标" @keyup.enter="load"/></label><button class="btn btn-ghost" :disabled="loading" @click="load"><AppIcon name="RefreshCw" :size="15"/>刷新</button></div><section class="panel table-wrap flux-table"><table><thead><tr><th v-for="c in config.columns" :key="c">{{columnName(c)}}</th><th class="right">操作</th></tr></thead><tbody><tr v-if="loading"><td :colspan="config.columns.length+1" class="empty">正在加载…</td></tr><tr v-else-if="!rows.length"><td :colspan="config.columns.length+1" class="empty">暂无配置，点击右上角新建</td></tr><tr v-for="row in rows" :key="row.id"><td v-for="c in config.columns" :key="c"><span v-if="['enabled','online'].includes(c)" class="status-pill" :class="{off:label(row,c).includes('停用')||label(row,c)==='离线'}">{{label(row,c)}}</span><template v-else>{{label(row,c)}}</template></td><td class="actions"><button class="btn btn-ghost btn-sm" @click="open(row)">编辑</button><button class="btn btn-danger btn-sm" @click="remove(row)">删除</button></td></tr></tbody></table></section><div class="pagination"><span>共 {{page.total}} 条</span><button class="btn btn-ghost btn-sm" :disabled="page.current<=1" @click="page.current--;load()">上一页</button><span>{{page.current}} / {{page.last}}</span><button class="btn btn-ghost btn-sm" :disabled="page.current>=page.last" @click="page.current++;load()">下一页</button></div></template>
  <div v-if="showForm" class="modal-backdrop" @click.self="showForm=false"><section class="modal-card flux-modal"><div class="panel-head"><div><h2>{{form.id?'编辑':'新建'}}{{config.title}}</h2><p>{{config.desc}}</p></div><button class="btn btn-ghost" @click="showForm=false">关闭</button></div><div class="smart-form"><label v-for="field in config.fields" :key="field[0]" class="field" :class="{'field-wide':field[2]==='textarea'}"><span>{{field[1]}}</span><ToggleSwitch v-if="field[2]==='switch'" v-model="form[field[0]]"/><textarea v-else-if="field[2]==='textarea'" v-model="form[field[0]]" rows="3"/><select v-else-if="choices(field[2]).length||['strategy','type','protocol','billing'].includes(field[2])" v-model="form[field[0]]"><option v-if="['limits'].includes(field[2])" :value="null">不限制</option><option v-for="o in choices(field[2])" :key="o.id" :value="o.id">{{optionText(field[2],o)}}</option><template v-if="field[2]==='strategy'"><option value="fifo">顺序</option><option value="round">轮询</option><option value="random">随机</option><option value="hash">哈希</option></template><template v-if="field[2]==='type'"><option :value="1">端口转发</option><option :value="2">隧道转发</option></template><template v-if="field[2]==='protocol'"><option v-for="p in ['tcp','udp','tls','ws','wss']" :key="p" :value="p">{{p.toUpperCase()}}</option></template><template v-if="field[2]==='billing'"><option :value="1">单向计费</option><option :value="2">双向计费</option></template></select><input v-else v-model="form[field[0]]" :type="field[2]" :min="field[2]==='number'?0:undefined"/></label></div><div class="modal-actions"><button class="btn btn-ghost" @click="showForm=false">取消</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'保存中…':'保存配置'}}</button></div></section></div><div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div>
</section></template>
