<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get, post } from '../services/http';

const groups = ref([]); const nodes = ref([]); const plans = ref([]); const loading = ref(true); const saving = ref(false); const busyId = ref(null); const keyword = ref(''); const usageFilter = ref('all'); const showForm = ref(false); const detail = ref(null);
const form = reactive({ id: null, name: '' }); const toast = reactive({ text: '', type: 'success' });
function enriched(group) { const linkedNodes = nodes.value.filter((node) => (node.group_ids || []).map(Number).includes(Number(group.id))); const linkedPlans = plans.value.filter((plan) => Number(plan.group_id) === Number(group.id)); return { ...group, linkedNodes, linkedPlans, used: Number(group.users_count || 0) > 0 || linkedNodes.length > 0 || linkedPlans.length > 0 }; }
const items = computed(() => groups.value.map(enriched));
const filtered = computed(() => items.value.filter((item) => { const term = keyword.value.trim().toLowerCase(); return (!term || item.name.toLowerCase().includes(term)) && (usageFilter.value === 'all' || (usageFilter.value === 'used' ? item.used : !item.used)); }));
const stats = computed(() => ({ total: groups.value.length, users: groups.value.reduce((sum, item) => sum + Number(item.users_count || 0), 0), nodes: new Set(items.value.flatMap((item) => item.linkedNodes.map((node) => node.id))).size, unused: items.value.filter((item) => !item.used).length }));
function notify(text, type = 'success') { toast.text = text; toast.type = type; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.text = ''; }, 2800); }
async function load() { loading.value = true; try { const [groupData, nodeData, planData] = await Promise.all([get('/server/group/fetch'), get('/server/manage/getNodes'), get('/plan/fetch')]); groups.value = Array.isArray(groupData) ? groupData : []; nodes.value = Array.isArray(nodeData) ? nodeData : []; plans.value = Array.isArray(planData) ? planData : []; } catch (e) { notify(e.message, 'error'); } finally { loading.value = false; } }
function createGroup() { Object.assign(form, { id: null, name: '' }); showForm.value = true; }
function editGroup(group) { Object.assign(form, { id: group.id, name: group.name }); showForm.value = true; }
function closeForm() { showForm.value = false; Object.assign(form, { id: null, name: '' }); }
async function save() { if (!form.name.trim()) return notify('权限组名称不能为空', 'error'); saving.value = true; try { await post('/server/group/save', { ...form }); notify(form.id ? '权限组已更新' : '权限组已创建'); closeForm(); await load(); } catch (e) { notify(e.message, 'error'); } finally { saving.value = false; } }
async function remove(group) { if (group.used) return notify('该权限组仍有关联用户、节点或套餐，无法删除', 'error'); if (!window.confirm(`确定删除权限组「${group.name}」？`)) return; busyId.value = group.id; try { await post('/server/group/drop', { id: group.id }); notify('权限组已删除'); await load(); } catch (e) { notify(e.message, 'error'); } finally { busyId.value = null; } }
function openDetail(group) { detail.value = group; }
function time(value) { return value ? new Date(Number(value) * 1000).toLocaleString('zh-CN', { hour12: false }) : '—'; }
onMounted(load);
</script>

<template><section class="page-stack">
  <div class="page-heading page-heading-row"><div><h1>权限组管理</h1><p>管理用户可访问的节点范围，并检查套餐、用户与节点关联。</p></div><button class="btn btn-primary" @click="createGroup"><AppIcon name="Plus" :size="16" />添加权限组</button></div>
  <div class="stat-grid group-stats"><article class="stat-card"><span>权限组</span><strong>{{ stats.total }}</strong></article><article class="stat-card"><span>关联用户</span><strong>{{ stats.users }}</strong></article><article class="stat-card"><span>已分配节点</span><strong>{{ stats.nodes }}</strong></article><article class="stat-card"><span>未使用组</span><strong>{{ stats.unused }}</strong></article></div>
  <div class="group-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" placeholder="权限组名称" /></label><label class="field compact-field"><span>使用状态</span><select v-model="usageFilter"><option value="all">全部状态</option><option value="used">正在使用</option><option value="unused">未使用</option></select></label><button class="btn btn-ghost" :disabled="loading" @click="load">刷新</button></div>
  <div class="panel group-guide"><AppIcon name="Info" :size="18" /><span>用户通过权限组获得节点访问范围；套餐绑定权限组后，购买该套餐的用户会继承对应权限。</span></div>
  <div v-if="loading" class="panel settings-loading">正在加载权限组…</div><div v-else-if="!filtered.length" class="panel settings-loading">暂无符合条件的权限组</div>
  <div v-else class="group-grid"><article v-for="group in filtered" :key="group.id" class="panel group-card"><div class="group-card-head"><div class="group-icon"><AppIcon name="Shield" :size="22" /></div><div><h2>{{ group.name }}</h2><span>#{{ group.id }} · {{ time(group.updated_at) }}</span></div><span class="status-pill" :class="{ off: !group.used }">{{ group.used ? '正在使用' : '未使用' }}</span></div><div class="group-counts"><button @click="openDetail(group)"><span>用户</span><strong>{{ group.users_count || 0 }}</strong></button><button @click="openDetail(group)"><span>节点</span><strong>{{ group.linkedNodes.length }}</strong></button><button @click="openDetail(group)"><span>套餐</span><strong>{{ group.linkedPlans.length }}</strong></button></div><div class="group-actions"><button class="btn btn-ghost btn-sm" @click="openDetail(group)">查看关联</button><button class="btn btn-ghost btn-sm" @click="editGroup(group)">重命名</button><button class="btn btn-danger btn-sm" :disabled="group.used || busyId === group.id" :title="group.used ? '请先解除用户、节点和套餐关联' : ''" @click="remove(group)">删除</button></div></article></div>
  <div v-if="showForm" class="modal-backdrop" @click.self="closeForm"><section class="modal-card group-modal"><div class="panel-head"><div><h2>{{ form.id ? '重命名权限组' : '添加权限组' }}</h2><p>创建后可在节点和订阅套餐中绑定该权限组。</p></div><button class="btn btn-ghost" @click="closeForm">关闭</button></div><label class="field"><span>权限组名称</span><input v-model.trim="form.name" placeholder="例如：高级线路" @keydown.enter.prevent="save" /></label><div class="modal-actions"><button class="btn btn-primary" :disabled="saving" @click="save">{{ saving ? '保存中…' : '保存权限组' }}</button></div></section></div>
  <div v-if="detail" class="modal-backdrop" @click.self="detail = null"><section class="modal-card group-detail"><div class="panel-head"><div><h2>{{ detail.name }} · 关联资源</h2><p>删除权限组前必须解除以下全部关联。</p></div><button class="btn btn-ghost" @click="detail = null">关闭</button></div><div class="group-detail-stats"><span>用户 <strong>{{ detail.users_count || 0 }}</strong></span><span>节点 <strong>{{ detail.linkedNodes.length }}</strong></span><span>套餐 <strong>{{ detail.linkedPlans.length }}</strong></span></div><h3>关联节点</h3><div v-if="detail.linkedNodes.length" class="group-resource-list"><div v-for="node in detail.linkedNodes" :key="node.id"><strong>{{ node.name }}</strong><code>{{ node.type }} · {{ node.host }}:{{ node.port }}</code><span class="status-pill" :class="{ off: !Number(node.show) }">{{ Number(node.show) ? '已上架' : '已下架' }}</span></div></div><div v-else class="settings-loading">暂无关联节点</div><h3>关联套餐</h3><div v-if="detail.linkedPlans.length" class="group-resource-list"><div v-for="plan in detail.linkedPlans" :key="plan.id"><strong>{{ plan.name }}</strong><span>{{ plan.users_count || 0 }} 位用户</span><span class="status-pill" :class="{ off: !Number(plan.show) }">{{ Number(plan.show) ? '销售中' : '已隐藏' }}</span></div></div><div v-else class="settings-loading">暂无关联套餐</div><div v-if="Number(detail.users_count)" class="group-user-note">另有 {{ detail.users_count }} 位用户直接绑定此权限组，请在用户管理中调整。</div></section></div>
  <div v-if="toast.text" class="toast" :class="{ error: toast.type === 'error' }">{{ toast.text }}</div>
</section></template>
