<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get, post } from '../services/http';

const articles = ref([]); const categories = ref([]); const loading = ref(true); const saving = ref(false); const busyId = ref(null);
const keyword = ref(''); const categoryFilter = ref(''); const statusFilter = ref('all'); const sorting = ref(false); const sortDirty = ref(false); const showForm = ref(false); const preview = ref(false);
const toast = reactive({ text: '', type: 'success' }); const form = reactive(defaultForm());
function defaultForm() { return { id: null, category: '', language: 'zh-CN', title: '', body: '', show: 1 }; }
const filtered = computed(() => articles.value.filter((item) => { const term = keyword.value.trim().toLowerCase(); return (!term || `${item.title} ${item.category}`.toLowerCase().includes(term)) && (!categoryFilter.value || item.category === categoryFilter.value) && (statusFilter.value === 'all' || Number(item.show) === Number(statusFilter.value)); }));
const displayed = computed(() => sorting.value ? articles.value : filtered.value);
const stats = computed(() => ({ total: articles.value.length, visible: articles.value.filter((item) => Number(item.show)).length, categories: new Set(articles.value.map((item) => item.category).filter(Boolean)).size }));
function notify(text, type = 'success') { toast.text = text; toast.type = type; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.text = ''; }, 2800); }
async function load() { loading.value = true; try { const [rows, groups] = await Promise.all([get('/knowledge/fetch'), get('/knowledge/getCategory')]); articles.value = Array.isArray(rows) ? rows : []; categories.value = Array.isArray(groups) ? groups.filter(Boolean) : []; } catch (e) { notify(e.message, 'error'); } finally { loading.value = false; } }
function createArticle() { Object.assign(form, defaultForm(), { category: categoryFilter.value || categories.value[0] || '' }); preview.value = false; showForm.value = true; }
async function editArticle(item) { busyId.value = item.id; try { const detail = await get('/knowledge/fetch', { id: item.id }); Object.assign(form, defaultForm(), detail); preview.value = false; showForm.value = true; } catch (e) { notify(e.message, 'error'); } finally { busyId.value = null; } }
function closeForm() { showForm.value = false; Object.assign(form, defaultForm()); preview.value = false; }
async function save() { if (!form.category.trim() || !form.language.trim() || !form.title.trim() || !form.body.trim()) return notify('分类、语言、标题和正文不能为空', 'error'); saving.value = true; try { await post('/knowledge/save', { ...form, show: Boolean(Number(form.show)) }); notify(form.id ? '文章已更新' : '文章已创建'); closeForm(); await load(); } catch (e) { notify(e.message, 'error'); } finally { saving.value = false; } }
async function toggle(item) { busyId.value = item.id; try { await post('/knowledge/show', { id: item.id }); item.show = !item.show; notify(item.show ? '文章已显示' : '文章已隐藏'); } catch (e) { notify(e.message, 'error'); } finally { busyId.value = null; } }
async function remove(item) { if (!window.confirm(`确定删除知识库文章「${item.title}」？此操作无法撤销。`)) return; busyId.value = item.id; try { await post('/knowledge/drop', { id: item.id }); notify('文章已删除'); await load(); } catch (e) { notify(e.message, 'error'); } finally { busyId.value = null; } }
function enterSorting() { sorting.value = !sorting.value; sortDirty.value = false; if (sorting.value) { keyword.value = ''; categoryFilter.value = ''; statusFilter.value = 'all'; } }
function move(index, direction) { const target = index + direction; if (target < 0 || target >= articles.value.length) return; const next = [...articles.value]; [next[index], next[target]] = [next[target], next[index]]; articles.value = next; sortDirty.value = true; }
async function saveSort() { saving.value = true; try { await post('/knowledge/sort', { ids: articles.value.map((item) => item.id) }); sorting.value = false; sortDirty.value = false; notify('文章排序已保存'); } catch (e) { notify(e.message, 'error'); } finally { saving.value = false; } }
function insertVariable(value) { form.body += `${form.body && !form.body.endsWith('\n') ? '\n' : ''}${value}`; }
function formatTime(value) { return value ? new Date(Number(value) * 1000).toLocaleString('zh-CN', { hour12: false }) : '—'; }
onMounted(load);
</script>

<template>
  <section class="page-stack">
    <div class="page-heading page-heading-row"><div><h1>知识库管理</h1><p>维护帮助文章、分类和多语言内容，并控制用户端展示顺序。</p></div><button class="btn btn-primary" @click="createArticle"><AppIcon name="Plus" :size="16" />添加文章</button></div>
    <div class="stat-grid knowledge-stats"><article class="stat-card"><span>文章总数</span><strong>{{ stats.total }}</strong></article><article class="stat-card"><span>显示中</span><strong>{{ stats.visible }}</strong></article><article class="stat-card"><span>分类数量</span><strong>{{ stats.categories }}</strong></article></div>
    <div class="knowledge-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" :disabled="sorting" placeholder="文章标题或分类" /></label><label class="field compact-field"><span>文章分类</span><select v-model="categoryFilter" :disabled="sorting"><option value="">全部分类</option><option v-for="category in categories" :key="category" :value="category">{{ category }}</option></select></label><label class="field compact-field"><span>显示状态</span><select v-model="statusFilter" :disabled="sorting"><option value="all">全部状态</option><option value="1">显示中</option><option value="0">已隐藏</option></select></label><button class="btn btn-ghost" @click="enterSorting">{{ sorting ? '退出排序' : '调整排序' }}</button><button v-if="sorting" class="btn btn-primary" :disabled="!sortDirty || saving" @click="saveSort">保存排序</button><button v-else class="btn btn-ghost" :disabled="loading" @click="load">刷新</button></div>
    <div v-if="sorting" class="panel knowledge-tip">排序模式会显示全部文章；上下移动后点击“保存排序”生效。</div>
    <div v-if="loading" class="panel settings-loading">正在加载知识库…</div><div v-else-if="!displayed.length" class="panel settings-loading">暂无符合条件的文章</div>
    <div v-else class="knowledge-list"><article v-for="(item, index) in displayed" :key="item.id" class="panel knowledge-card">
      <div v-if="sorting" class="sort-controls"><button class="icon-button" title="上移" :disabled="index === 0" @click="move(index, -1)"><AppIcon name="ArrowUp" :size="16" /></button><button class="icon-button" title="下移" :disabled="index === articles.length - 1" @click="move(index, 1)"><AppIcon name="ArrowDown" :size="16" /></button></div>
      <div class="knowledge-mark"><AppIcon name="BookOpen" :size="21" /></div><div class="knowledge-body"><div class="knowledge-head"><div><span class="knowledge-category">{{ item.category }}</span><h2>{{ item.title }}</h2><small>#{{ item.id }} · 更新于 {{ formatTime(item.updated_at) }}</small></div><span class="status-pill" :class="{ off: !Number(item.show) }">{{ Number(item.show) ? '显示中' : '已隐藏' }}</span></div></div>
      <div class="knowledge-actions"><button class="btn btn-ghost btn-sm" :disabled="busyId === item.id" @click="toggle(item)">{{ Number(item.show) ? '隐藏' : '显示' }}</button><button class="btn btn-ghost btn-sm" :disabled="busyId === item.id" @click="editArticle(item)">编辑</button><button class="btn btn-danger btn-sm" :disabled="busyId === item.id" @click="remove(item)">删除</button></div>
    </article></div>
    <div v-if="showForm" class="modal-backdrop" @click.self="closeForm"><section class="modal-card knowledge-modal"><div class="panel-head"><div><h2>{{ form.id ? '编辑文章' : '添加文章' }}</h2><p>正文支持 Markdown 或 HTML，并可插入用户专属变量。</p></div><button class="btn btn-ghost" @click="closeForm">关闭</button></div><div class="smart-form"><label class="field"><span>文章分类</span><input v-model.trim="form.category" list="knowledge-categories" placeholder="例如：使用教程" /><datalist id="knowledge-categories"><option v-for="category in categories" :key="category" :value="category" /></datalist></label><label class="field"><span>内容语言</span><input v-model.trim="form.language" list="knowledge-languages" placeholder="zh-CN" /><datalist id="knowledge-languages"><option value="zh-CN" /><option value="zh-TW" /><option value="en-US" /><option value="ja-JP" /></datalist></label><label class="field field-wide"><span>文章标题</span><input v-model.trim="form.title" placeholder="请输入文章标题" /></label><label class="field"><span>显示状态</span><select v-model.number="form.show"><option :value="1">显示</option><option :value="0">隐藏</option></select></label></div>
      <div class="knowledge-editor"><div class="knowledge-editor-bar"><div class="editor-tabs"><button type="button" :class="{ active: !preview }" @click="preview = false">编辑</button><button type="button" :class="{ active: preview }" @click="preview = true">文本预览</button></div><div class="variable-buttons"><button type="button" @click="insertVariable('{{siteName}}')">站点名称</button><button type="button" @click="insertVariable('{{subscribeUrl}}')">订阅地址</button><button type="button" @click="insertVariable('{{urlEncodeSubscribeUrl}}')">URL 编码订阅</button></div></div><textarea v-if="!preview" v-model="form.body" placeholder="请输入文章正文" /><pre v-else>{{ form.body || '暂无内容' }}</pre><small>需要订阅后才能查看的内容，可放在 &lt;!--access start--&gt; 与 &lt;!--access end--&gt; 之间。</small></div>
      <div class="modal-actions"><button class="btn btn-primary" :disabled="saving" @click="save">{{ saving ? '保存中…' : '保存文章' }}</button></div></section></div>
    <div v-if="toast.text" class="toast" :class="{ error: toast.type === 'error' }">{{ toast.text }}</div>
  </section>
</template>
