<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get } from '../services/http';

const rows=ref([]);const loading=ref(true);const keyword=ref('');const typeFilter=ref('');const healthFilter=ref('all');const includeHidden=ref(false);const detail=ref(null);const detailTab=ref('users');const usersPayload=ref(null);const accessPayload=ref(null);const detailLoading=ref(false);const detailSearch=ref('');const toast=reactive({text:'',type:'success'});
const filtered=computed(()=>rows.value.filter(row=>{const term=keyword.value.trim().toLowerCase();return(!term||`${row.node_name} ${row.node_type} ${row.group_names} ${row.abnormal_reason}`.toLowerCase().includes(term))&&(!typeFilter.value||row.node_type===typeFilter.value)&&(healthFilter.value==='all'||row.abnormal_status===healthFilter.value);}));
const types=computed(()=>[...new Set(rows.value.map(row=>row.node_type).filter(Boolean))]);
const stats=computed(()=>({total:rows.value.length,online:rows.value.filter(r=>r.node_status==='online').length,abnormal:rows.value.filter(r=>r.abnormal_status!=='normal').length,users:rows.value.reduce((s,r)=>s+Number(r.fetched_users||0),0),excluded:rows.value.reduce((s,r)=>s+Number(r.excluded_banned||0)+Number(r.excluded_expired||0)+Number(r.excluded_traffic||0),0)}));
const shownUsers=computed(()=>{const list=usersPayload.value?.users||[];const term=detailSearch.value.trim().toLowerCase();return term?list.filter(u=>`${u.email} ${u.xray_email} ${u.uuid} ${u.reason_label}`.toLowerCase().includes(term)):list;});
const shownAccess=computed(()=>{const list=accessPayload.value?.access||[];const term=detailSearch.value.trim().toLowerCase();return term?list.filter(a=>`${a.email} ${a.source} ${a.destination} ${a.network}`.toLowerCase().includes(term)):list;});
function notify(text,type='success'){toast.text=text;toast.type=type;window.clearTimeout(notify.timer);notify.timer=window.setTimeout(()=>{toast.text='';},2800);}
async function load(){loading.value=true;try{const data=await get('/node-sync-diagnostic/snapshots',{include_hidden:includeHidden.value?1:0,pageSize:100,current:1,sort_field:'synced_at',sort_order:'desc'});rows.value=Array.isArray(data)?data:[];}catch(e){notify(e.message,'error');}finally{loading.value=false;}}
async function openDetail(row){detail.value=row;detailTab.value='users';detailSearch.value='';detailLoading.value=true;usersPayload.value=null;accessPayload.value=null;try{const [userData,accessData]=await Promise.all([get('/node-sync-diagnostic/node-users',{node_id:row.node_id}),get('/node-sync-diagnostic/access',{node_id:row.node_id,limit:200})]);usersPayload.value=userData;accessPayload.value=accessData;}catch(e){notify(e.message,'error');}finally{detailLoading.value=false;}}
function healthLabel(value){return{normal:'正常',warning:'警告',blocked:'已阻断'}[value]||value;}
function nodeLabel(value){return{online:'在线',online_no_push:'在线未推送',offline:'离线'}[value]||value;}
function time(value){return value?new Date(Number(value)*1000).toLocaleString('zh-CN',{hour12:false}):'暂无记录';}
function bytes(value){const n=Number(value||0);if(!n)return'0 B';const u=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return`${(n/1024**i).toFixed(i>2?1:0)} ${u[i]}`;}
function trafficPercent(user){return user.transfer_enable?Math.min(100,Math.round(Number(user.used_traffic||0)/Number(user.transfer_enable)*100)):100;}
onMounted(load);
</script>

<template><section class="page-stack">
  <div class="page-heading page-heading-row"><div><h1>节点数据分析</h1><p>检查节点在线状态、用户同步差异、排除原因和近期访问记录。</p></div><button class="btn btn-ghost" :disabled="loading" @click="load"><AppIcon name="RefreshCw" :size="16" />刷新诊断</button></div>
  <div class="stat-grid diagnostic-stats"><article class="stat-card"><span>诊断节点</span><strong>{{stats.total}}</strong></article><article class="stat-card"><span>在线节点</span><strong>{{stats.online}}</strong></article><article class="stat-card"><span>异常节点</span><strong>{{stats.abnormal}}</strong></article><article class="stat-card"><span>同步用户</span><strong>{{stats.users}}</strong></article><article class="stat-card"><span>被排除用户</span><strong>{{stats.excluded}}</strong></article></div>
  <div class="diagnostic-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" placeholder="节点、协议、权限组或异常原因" /></label><label class="field compact-field"><span>协议</span><select v-model="typeFilter"><option value="">全部协议</option><option v-for="type in types" :key="type">{{type}}</option></select></label><label class="field compact-field"><span>同步健康</span><select v-model="healthFilter"><option value="all">全部状态</option><option value="normal">正常</option><option value="warning">警告</option><option value="blocked">已阻断</option></select></label><label class="diagnostic-toggle"><input v-model="includeHidden" type="checkbox" @change="load" />包含已下架节点</label></div>
  <div class="panel diagnostic-guide"><AppIcon name="ShieldCheck" :size="18" /><span>此页面完全只读。异常通常来自权限组不匹配、封禁、套餐过期、流量耗尽或同步用户数突变。</span></div>
  <div v-if="loading" class="panel settings-loading">正在读取节点诊断快照…</div><div v-else-if="!filtered.length" class="panel settings-loading">暂无符合条件的诊断数据</div>
  <div v-else class="diagnostic-grid"><article v-for="row in filtered" :key="row.node_id" class="panel diagnostic-card" :class="row.abnormal_status"><div class="diagnostic-head"><div class="diagnostic-icon"><AppIcon name="Activity" :size="21" /></div><div><h2>{{row.node_name}}</h2><span>#{{row.node_id}} · {{row.node_type}} · {{row.group_names||'未分组'}}</span></div><span class="diagnostic-health" :class="row.abnormal_status">{{healthLabel(row.abnormal_status)}}</span></div><div class="diagnostic-node-state"><span class="status-pill" :class="{off:row.node_status==='offline'}">{{nodeLabel(row.node_status)}}</span><span>{{row.online_users}} 位在线用户</span><span>{{row.online_connections}} 个连接</span><span>机器 #{{row.machine_id||'—'}}</span></div><div class="sync-flow"><div><small>上次用户</small><strong>{{row.previous_users}}</strong></div><i>→</i><div><small>本次同步</small><strong>{{row.fetched_users}}</strong></div><span class="sync-added">+{{row.added}}</span><span class="sync-removed">-{{row.removed}}</span></div><div class="exclusion-grid"><span>封禁排除<strong>{{row.excluded_banned}}</strong></span><span>过期排除<strong>{{row.excluded_expired}}</strong></span><span>流量排除<strong>{{row.excluded_traffic}}</strong></span></div><div v-if="row.abnormal_reason" class="diagnostic-reason"><AppIcon name="TriangleAlert" :size="15" />{{row.abnormal_reason}}</div><div class="diagnostic-meta"><span>同步：{{time(row.synced_at)}}</span><span>检查：{{time(row.last_check_at)}}</span></div><button class="btn btn-ghost diagnostic-detail-button" @click="openDetail(row)">查看用户与访问详情</button></article></div>
  <div v-if="detail" class="modal-backdrop" @click.self="detail=null"><section class="modal-card diagnostic-modal"><div class="panel-head"><div><h2>{{detail.node_name}} · 诊断详情</h2><p>{{detail.node_type}} · 最近同步 {{time(detail.synced_at)}}</p></div><button class="btn btn-ghost" @click="detail=null">关闭</button></div><div class="diagnostic-tabs"><button :class="{active:detailTab==='users'}" @click="detailTab='users';detailSearch=''">同步用户（{{usersPayload?.summary?.total||0}}）</button><button :class="{active:detailTab==='access'}" @click="detailTab='access';detailSearch=''">访问记录（{{accessPayload?.total||0}}）</button></div><label class="filter-input diagnostic-search"><span>筛选当前详情</span><input v-model="detailSearch" :placeholder="detailTab==='users'?'邮箱、UUID 或不可用原因':'用户、来源或目标地址'" /></label><div v-if="detailLoading" class="settings-loading">正在读取诊断详情…</div>
    <template v-else-if="detailTab==='users'"><div class="detail-summary"><span>在线<strong>{{usersPayload?.summary?.online||0}}</strong></span><span>离线<strong>{{usersPayload?.summary?.offline||0}}</strong></span><span>不可用<strong>{{usersPayload?.summary?.unavailable||0}}</strong></span><span>未在当前同步<strong>{{usersPayload?.summary?.not_current_sync||0}}</strong></span></div><div class="diagnostic-table"><table><thead><tr><th>用户</th><th>状态</th><th>同步</th><th>流量</th><th>连接/设备</th><th>到期时间</th></tr></thead><tbody><tr v-for="user in shownUsers" :key="user.id"><td><strong>{{user.email}}</strong><small>#{{user.id}} · {{user.xray_email}}</small></td><td><span class="status-pill" :class="{off:user.status!=='online'}">{{user.status==='online'?'在线':user.status==='offline'?'离线':'不可用'}}</span><small v-if="!user.available_now">{{user.reason_label}}</small></td><td><strong>{{user.included_in_current_sync?'当前已包含':'当前未包含'}}</strong><small>上次：{{user.included_in_last_sync===null?'未知':user.included_in_last_sync?'已包含':'未包含'}}</small></td><td><strong>{{bytes(user.used_traffic)}} / {{bytes(user.transfer_enable)}}</strong><small>{{trafficPercent(user)}}%</small></td><td>{{user.connections}} / {{user.node_devices}}</td><td>{{user.expired_at_text}}</td></tr></tbody></table><div v-if="!shownUsers.length" class="settings-loading">暂无符合条件的用户</div></div></template>
    <template v-else><div class="diagnostic-table"><table><thead><tr><th>时间</th><th>用户</th><th>来源</th><th>目标</th><th>网络</th><th>流量</th></tr></thead><tbody><tr v-for="item in shownAccess" :key="`${item.session_id}-${item.timestamp}`"><td>{{time(item.timestamp)}}</td><td><strong>{{item.email||item.xray_email}}</strong><small>#{{item.user_id}}</small></td><td><code>{{item.source||'—'}}</code></td><td><code>{{item.destination||'—'}}</code></td><td>{{item.network||'—'}}</td><td>{{bytes(item.total)}}</td></tr></tbody></table><div v-if="!shownAccess.length" class="settings-loading">暂无符合条件的访问记录</div></div></template>
  </section></div><div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div>
</section></template>
