<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get, post } from '../services/http';

const TYPES = ['hysteria','vless','trojan','vmess','tuic','shadowsocks','anytls','socks','naive','http','mieru'];
const nodes = ref([]); const groups = ref([]); const routes = ref([]); const machines = ref([]); const selected = ref([]); const loading = ref(true); const saving = ref(false); const busyId = ref(null);
const keyword = ref(''); const typeFilter = ref(''); const statusFilter = ref('all'); const sorting = ref(false); const sortDirty = ref(false); const showForm = ref(false); const advanced = ref(false); const protocolJson = ref('{}');
const toast = reactive({ text: '', type: 'success' }); const form = reactive(defaultForm());
function defaults(type = 'vless') { return { shadowsocks:{cipher:'2022-blake3-aes-128-gcm'}, vmess:{tls:1,network:'tcp'}, trojan:{tls:1,network:'tcp'}, hysteria:{version:2}, vless:{tls:1,network:'tcp'}, socks:{tls:0}, naive:{tls:1}, http:{tls:1}, tuic:{version:5}, mieru:{transport:'TCP',traffic_pattern:''}, anytls:{} }[type] || {}; }
function defaultForm() { return { id:null,type:'vless',name:'',host:'',port:443,server_port:443,rate:1,show:true,enabled:true,machine_id:null,parent_id:null,group_ids:[],route_ids:[],tags:[],transfer_enable:0,protocol_settings:defaults('vless') }; }
const filtered = computed(() => nodes.value.filter((item) => { const term = keyword.value.trim().toLowerCase(); return (!term || `${item.name} ${item.host} ${item.type}`.toLowerCase().includes(term)) && (!typeFilter.value || item.type === typeFilter.value) && (statusFilter.value === 'all' || (statusFilter.value === 'online' ? Number(item.is_online) : statusFilter.value === 'visible' ? Number(item.show) : !Number(item.enabled))); }));
const displayed = computed(() => sorting.value ? nodes.value : filtered.value); const allSelected = computed(() => displayed.value.length > 0 && displayed.value.every((item) => selected.value.includes(item.id)));
const stats = computed(() => ({ total:nodes.value.length, online:nodes.value.filter((item)=>Number(item.is_online)).length, visible:nodes.value.filter((item)=>Number(item.show)).length, traffic:nodes.value.reduce((sum,item)=>sum+Number(item.u||0)+Number(item.d||0),0) }));
function notify(text,type='success'){toast.text=text;toast.type=type;window.clearTimeout(notify.timer);notify.timer=window.setTimeout(()=>{toast.text='';},2800);}
function bytes(value){const n=Number(value||0);if(!n)return'0 B';const u=['B','KB','MB','GB','TB','PB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return`${(n/1024**i).toFixed(i>2?1:0)} ${u[i]}`;}
async function load(){loading.value=true;try{const [nodeData,groupData,routeData,machineData]=await Promise.all([get('/server/manage/getNodes'),get('/server/group/fetch'),get('/server/route/fetch'),get('/server/machine/fetch')]);nodes.value=Array.isArray(nodeData)?nodeData:[];groups.value=Array.isArray(groupData)?groupData:[];routes.value=Array.isArray(routeData)?routeData:[];machines.value=Array.isArray(machineData)?machineData:[];selected.value=selected.value.filter(id=>nodes.value.some(n=>n.id===id));}catch(e){notify(e.message,'error');}finally{loading.value=false;}}
function createNode(){Object.assign(form,defaultForm());protocolJson.value=JSON.stringify(form.protocol_settings,null,2);advanced.value=false;showForm.value=true;}
function editNode(item){Object.assign(form,defaultForm(),item,{group_ids:[...(item.group_ids||[])],route_ids:[...(item.route_ids||[])],tags:[...(item.tags||[])]});protocolJson.value=JSON.stringify(item.protocol_settings||defaults(item.type),null,2);advanced.value=false;showForm.value=true;}
function changeType(){form.protocol_settings=defaults(form.type);protocolJson.value=JSON.stringify(form.protocol_settings,null,2);}
function closeForm(){showForm.value=false;Object.assign(form,defaultForm());}
async function save(){if(!form.name.trim()||!form.host.trim()||!form.port||!form.server_port)return notify('名称、地址和端口不能为空','error');let protocol;try{protocol=JSON.parse(protocolJson.value||'{}');}catch{return notify('协议参数不是有效 JSON','error');}saving.value=true;try{await post('/server/manage/save',{...form,machine_id:form.machine_id||null,parent_id:form.parent_id||null,show:Number(form.show),enabled:Boolean(form.enabled),protocol_settings:protocol});notify(form.id?'节点已更新':'节点已创建');closeForm();await load();}catch(e){notify(e.message,'error');}finally{saving.value=false;}}
async function quickUpdate(item,field,value){busyId.value=item.id;try{await post('/server/manage/update',{id:item.id,[field]:value});item[field]=value;notify(field==='show'?(value?'节点已上架':'节点已下架'):(value?'节点运行已启用':'节点运行已停用'));}catch(e){notify(e.message,'error');}finally{busyId.value=null;}}
async function copyNode(item){if(!window.confirm(`复制节点「${item.name}」？副本默认下架。`))return;busyId.value=item.id;try{await post('/server/manage/copy',{id:item.id});notify('节点已复制');await load();}catch(e){notify(e.message,'error');}finally{busyId.value=null;}}
async function resetTraffic(item){if(!window.confirm(`确定清零「${item.name}」的上下行流量？`))return;busyId.value=item.id;try{await post('/server/manage/resetTraffic',{id:item.id});notify('节点流量已清零');await load();}catch(e){notify(e.message,'error');}finally{busyId.value=null;}}
async function remove(item){if(!window.confirm(`确定删除节点「${item.name}」？此操作无法撤销。`))return;busyId.value=item.id;try{await post('/server/manage/drop',{id:item.id});notify('节点已删除');await load();}catch(e){notify(e.message,'error');}finally{busyId.value=null;}}
function toggleAll(){const ids=displayed.value.map(item=>item.id);selected.value=allSelected.value?selected.value.filter(id=>!ids.includes(id)):[...new Set([...selected.value,...ids])];}
async function batch(action){if(!selected.value.length)return;const labels={show:'批量上架',hide:'批量下架',enable:'批量启用运行',disable:'批量停用运行',reset:'批量清零流量',delete:'批量删除'};if(!window.confirm(`确定${labels[action]}选中的 ${selected.value.length} 个节点？`))return;saving.value=true;try{if(action==='delete')await post('/server/manage/batchDelete',{ids:selected.value});else if(action==='reset')await post('/server/manage/batchResetTraffic',{ids:selected.value});else await post('/server/manage/batchUpdate',{ids:selected.value,...(action==='show'||action==='hide'?{show:action==='show'?1:0}:{enabled:action==='enable'})});notify(`${labels[action]}成功`);selected.value=[];await load();}catch(e){notify(e.message,'error');}finally{saving.value=false;}}
function enterSorting(){sorting.value=!sorting.value;sortDirty.value=false;if(sorting.value){keyword.value='';typeFilter.value='';statusFilter.value='all';}}
function move(index,direction){const target=index+direction;if(target<0||target>=nodes.value.length)return;const next=[...nodes.value];[next[index],next[target]]=[next[target],next[index]];nodes.value=next;sortDirty.value=true;}
async function saveSort(){saving.value=true;try{await post('/server/manage/sort',nodes.value.map((item,index)=>({id:item.id,order:index+1})));sorting.value=false;sortDirty.value=false;notify('节点排序已保存');}catch(e){notify(e.message,'error');}finally{saving.value=false;}}
onMounted(load);
</script>

<template><section class="page-stack">
  <div class="page-heading page-heading-row"><div><h1>节点管理</h1><p>统一管理节点协议、入口参数、权限、机器绑定和运行状态。</p></div><button class="btn btn-primary" @click="createNode"><AppIcon name="Plus" :size="16" />添加节点</button></div>
  <div class="stat-grid node-stats"><article class="stat-card"><span>节点总数</span><strong>{{stats.total}}</strong></article><article class="stat-card"><span>在线节点</span><strong>{{stats.online}}</strong></article><article class="stat-card"><span>已上架</span><strong>{{stats.visible}}</strong></article><article class="stat-card"><span>累计流量</span><strong>{{bytes(stats.traffic)}}</strong></article></div>
  <div class="node-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" :disabled="sorting" placeholder="节点名称、地址或协议" /></label><label class="field compact-field"><span>协议</span><select v-model="typeFilter" :disabled="sorting"><option value="">全部协议</option><option v-for="type in TYPES" :key="type">{{type}}</option></select></label><label class="field compact-field"><span>状态</span><select v-model="statusFilter" :disabled="sorting"><option value="all">全部状态</option><option value="online">在线</option><option value="visible">已上架</option><option value="disabled">运行已停用</option></select></label><button class="btn btn-ghost" @click="enterSorting">{{sorting?'退出排序':'调整排序'}}</button><button v-if="sorting" class="btn btn-primary" :disabled="!sortDirty||saving" @click="saveSort">保存排序</button><button v-else class="btn btn-ghost" :disabled="loading" @click="load">刷新</button></div>
  <div v-if="selected.length" class="panel batch-bar"><strong>已选择 {{selected.length}} 个节点</strong><div><button class="btn btn-ghost btn-sm" @click="batch('show')">上架</button><button class="btn btn-ghost btn-sm" @click="batch('hide')">下架</button><button class="btn btn-ghost btn-sm" @click="batch('enable')">启用运行</button><button class="btn btn-ghost btn-sm" @click="batch('disable')">停用运行</button><button class="btn btn-ghost btn-sm" @click="batch('reset')">清零流量</button><button class="btn btn-danger btn-sm" @click="batch('delete')">删除</button></div></div>
  <div v-if="loading" class="panel settings-loading">正在加载节点…</div><div v-else-if="!displayed.length" class="panel settings-loading">暂无符合条件的节点</div>
  <div v-else class="panel node-table"><div class="table-wrap"><table><thead><tr><th><input type="checkbox" :checked="allSelected" @change="toggleAll" /></th><th>节点</th><th>入口</th><th>权限组</th><th>运行状态</th><th>流量 / 倍率</th><th class="right">操作</th></tr></thead><tbody><tr v-for="(item,index) in displayed" :key="item.id"><td><div class="node-sort-select"><input v-model="selected" type="checkbox" :value="item.id" /><div v-if="sorting" class="sort-controls inline"><button class="icon-button" title="上移" :disabled="index===0" @click="move(index,-1)"><AppIcon name="ArrowUp" :size="14" /></button><button class="icon-button" title="下移" :disabled="index===nodes.length-1" @click="move(index,1)"><AppIcon name="ArrowDown" :size="14" /></button></div></div></td><td><strong>{{item.name}}</strong><small>#{{item.id}} · {{item.type}}<span v-if="item.parent"> · 子节点：{{item.parent.name}}</span></small></td><td><code>{{item.host}}:{{item.port}}</code><small>服务端口 {{item.server_port}}</small></td><td><div class="node-groups"><span v-for="group in item.groups" :key="group.id">{{group.name}}</span><small v-if="!item.groups?.length">未分配</small></div></td><td><div class="node-statuses"><span class="status-pill" :class="{off:!Number(item.is_online)}">{{Number(item.is_online)?'在线':'离线'}}</span><span class="status-pill" :class="{off:!Number(item.show)}">{{Number(item.show)?'已上架':'已下架'}}</span><span class="status-pill" :class="{off:!item.enabled}">{{item.enabled?'运行中':'已停用'}}</span></div></td><td><strong>{{bytes(Number(item.u||0)+Number(item.d||0))}}</strong><small>倍率 × {{item.rate}}</small></td><td><div class="actions node-actions"><button class="btn btn-ghost btn-sm" :disabled="busyId===item.id" @click="quickUpdate(item,'show',Number(item.show)?0:1)">{{Number(item.show)?'下架':'上架'}}</button><button class="btn btn-ghost btn-sm" @click="editNode(item)">编辑</button><button class="btn btn-ghost btn-sm" :disabled="busyId===item.id" @click="copyNode(item)">复制</button><details><summary>更多</summary><div><button @click="quickUpdate(item,'enabled',!item.enabled)">{{item.enabled?'停用运行':'启用运行'}}</button><button @click="resetTraffic(item)">清零流量</button><button class="danger" @click="remove(item)">删除节点</button></div></details></div></td></tr></tbody></table></div></div>
  <div v-if="showForm" class="modal-backdrop" @click.self="closeForm"><section class="modal-card node-modal"><div class="panel-head"><div><h2>{{form.id?'编辑节点':'添加节点'}}</h2><p>基础入口与关联配置；高级区用于协议特有参数。</p></div><button class="btn btn-ghost" @click="closeForm">关闭</button></div><div class="smart-form"><label class="field"><span>节点名称</span><input v-model.trim="form.name" placeholder="例如：香港 IEPL 01" /></label><label class="field"><span>协议类型</span><select v-model="form.type" :disabled="Boolean(form.id)" @change="changeType"><option v-for="type in TYPES" :key="type">{{type}}</option></select></label><label class="field"><span>连接地址</span><input v-model.trim="form.host" placeholder="域名或 IP" /></label><label class="field"><span>用户端口</span><input v-model.number="form.port" type="number" min="1" max="65535" /></label><label class="field"><span>服务端口</span><input v-model.number="form.server_port" type="number" min="1" max="65535" /></label><label class="field"><span>流量倍率</span><input v-model.number="form.rate" type="number" min="0" step="0.1" /></label><label class="field"><span>所属机器</span><select v-model="form.machine_id"><option :value="null">不绑定</option><option v-for="machine in machines" :key="machine.id" :value="machine.id">{{machine.name}}</option></select></label><label class="field"><span>父节点</span><select v-model="form.parent_id"><option :value="null">无父节点</option><option v-for="node in nodes.filter(n=>n.id!==form.id)" :key="node.id" :value="node.id">{{node.name}}</option></select></label><label class="field"><span>用户端展示</span><select v-model="form.show"><option :value="true">上架</option><option :value="false">下架</option></select></label><label class="field"><span>运行状态</span><select v-model="form.enabled"><option :value="true">启用</option><option :value="false">停用</option></select></label><label class="field"><span>权限组（可多选）</span><select v-model="form.group_ids" multiple><option v-for="group in groups" :key="group.id" :value="group.id">{{group.name}}</option></select></label><label class="field"><span>路由规则（可多选）</span><select v-model="form.route_ids" multiple><option v-for="route in routes" :key="route.id" :value="route.id">{{route.remarks||`路由 #${route.id}`}}</option></select></label><label class="field field-wide"><span>标签（每行一个）</span><textarea :value="form.tags.join('\n')" rows="3" @input="form.tags=$event.target.value.split('\n').map(v=>v.trim()).filter(Boolean)" /></label><label class="field"><span>流量上限（字节）</span><input v-model.number="form.transfer_enable" type="number" min="0" /><small>0 表示不限制</small></label></div><button class="advanced-toggle" @click="advanced=!advanced">{{advanced?'收起':'展开'}}高级协议参数</button><label v-if="advanced" class="field protocol-json"><span>protocol_settings JSON</span><textarea v-model="protocolJson" rows="14" spellcheck="false" /></label><div class="modal-actions"><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'保存中…':'保存节点'}}</button></div></section></div>
  <div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div>
</section></template>
