<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get, post, request } from '../services/http';

const STATUS = { 0: ['待支付','waiting'], 1: ['开通中','waiting'], 2: ['已取消','off'], 3: ['已完成',''], 4: ['已折抵','off'] };
const TYPES = { 1:'新购', 2:'续费', 3:'升级', 4:'流量重置' };
const PERIODS = { month_price:'月付',quarter_price:'季付',half_year_price:'半年付',year_price:'年付',two_year_price:'两年付',three_year_price:'三年付',onetime_price:'一次性',reset_price:'重置流量' };
const orders=ref([]),plans=ref([]),loading=ref(false),busy=ref(''),detail=ref(null),showAssign=ref(false),assigning=ref(false);
const filters=reactive({keyword:'',status:'all',type:'all',plan_id:''});
const page=reactive({current:1,size:20,total:0,last:1});
const toast=reactive({text:'',type:'success'});
const assign=reactive({email:'',plan_id:'',period:'',total_yuan:0});
const currentPlan=computed(()=>plans.value.find(p=>Number(p.id)===Number(assign.plan_id)));
const assignPeriods=computed(()=>Object.entries(PERIODS).filter(([key])=>Number(currentPlan.value?.prices?.[key.replace('_price','')]||currentPlan.value?.prices?.[{month_price:'monthly',quarter_price:'quarterly',half_year_price:'half_yearly',year_price:'yearly',two_year_price:'two_yearly',three_year_price:'three_yearly',onetime_price:'onetime',reset_price:'reset_traffic'}[key]])>0));
const stats=computed(()=>({total:orders.value.length,pending:orders.value.filter(o=>Number(o.status)===0).length,completed:orders.value.filter(o=>Number(o.status)===3).length,amount:orders.value.filter(o=>Number(o.status)===3).reduce((s,o)=>s+Number(o.total_amount||0),0)}));
function notify(text,type='success'){toast.text=text;toast.type=type;clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.text='',2800)}
function money(cents){return `¥${(Number(cents||0)/100).toFixed(2)}`}
function time(v){return v?new Date(Number(v)*1000).toLocaleString('zh-CN',{hour12:false}):'-'}
function status(o){return STATUS[Number(o.status)]||['未知','off']}
function makeQuery(){const q=new URLSearchParams({current:String(page.current),pageSize:String(page.size)});let i=0;const add=(id,value)=>{if(value===''||value==='all')return;q.set(`filter[${i}][id]`,id);q.set(`filter[${i}][value]`,String(value));i++};if(filters.keyword){const isTrade=/^[A-Za-z0-9_-]{8,}$/.test(filters.keyword);add(isTrade?'trade_no':'user_id',isTrade?filters.keyword:`like:${filters.keyword}`)}add('status',filters.status);add('type',filters.type);add('plan_id',filters.plan_id);return q.toString()}
async function load(reset=false){if(reset)page.current=1;loading.value=true;try{const data=await request(`/order/fetch?${makeQuery()}`);const source=data?.data??data;orders.value=source?.items||source?.data||(Array.isArray(source)?source:[]);page.total=Number(source?.total||orders.value.length);page.current=Number(source?.current_page||page.current);page.last=Number(source?.last_page||Math.max(1,Math.ceil(page.total/page.size)));}catch(e){notify(e.message,'error')}finally{loading.value=false}}
async function loadPlans(){try{const data=await get('/plan/fetch');plans.value=Array.isArray(data)?data:[]}catch(e){notify(e.message,'error')}}
async function openDetail(order){busy.value=order.trade_no;try{detail.value=await post('/order/detail',{id:order.id})}catch(e){notify(e.message,'error')}finally{busy.value=''}}
async function act(order,kind){const label=kind==='paid'?'手动标记已支付':'取消';if(!confirm(`确定${label}订单 ${order.trade_no}？${kind==='paid'?'此操作会立即执行开通流程，无法直接撤销。':''}`))return;busy.value=order.trade_no;try{await post(`/order/${kind}`,{trade_no:order.trade_no});notify(`订单已${kind==='paid'?'标记支付':'取消'}`);await load()}catch(e){notify(e.message,'error')}finally{busy.value=''}}
function startAssign(){Object.assign(assign,{email:'',plan_id:plans.value[0]?.id||'',period:'',total_yuan:0});syncAssignPeriod();showAssign.value=true}
function syncAssignPeriod(){assign.period=assignPeriods.value[0]?.[0]||'';const key={month_price:'monthly',quarter_price:'quarterly',half_year_price:'half_yearly',year_price:'yearly',two_year_price:'two_yearly',three_year_price:'three_yearly',onetime_price:'onetime',reset_price:'reset_traffic'}[assign.period];assign.total_yuan=Number(currentPlan.value?.prices?.[key]||0)}
async function saveAssign(){if(!assign.email||!assign.plan_id||!assign.period)return notify('请完整填写用户、套餐和周期','error');if(Number(assign.total_yuan)<0)return notify('支付金额不能小于 0','error');if(!confirm(`确定为 ${assign.email} 分配套餐？订单金额为 ${money(Number(assign.total_yuan)*100)}。`))return;assigning.value=true;try{const trade=await post('/order/assign',{email:assign.email,plan_id:assign.plan_id,period:assign.period,total_amount:Math.round(Number(assign.total_yuan)*100)});notify(`订单已创建：${trade}`);showAssign.value=false;await load(true)}catch(e){notify(e.message,'error')}finally{assigning.value=false}}
onMounted(()=>Promise.all([load(true),loadPlans()]));
</script>
<template><section class="page-stack"><div class="page-heading page-heading-row"><div><h1>订单管理</h1><p>查询订单、核对支付明细，并处理待支付订单和人工分配。</p></div><button class="btn btn-primary" @click="startAssign"><AppIcon name="Plus" :size="16"/>人工分配</button></div>
<div class="stat-grid order-stats"><article class="stat-card"><span>当前页订单</span><strong>{{stats.total}}</strong></article><article class="stat-card"><span>当前页待支付</span><strong>{{stats.pending}}</strong></article><article class="stat-card"><span>当前页已完成</span><strong>{{stats.completed}}</strong></article><article class="stat-card"><span>当前页成交额</span><strong>{{money(stats.amount)}}</strong></article></div>
<section class="panel"><div class="order-toolbar"><label class="filter-input"><span>订单号 / 用户 ID</span><input v-model.trim="filters.keyword" placeholder="输入订单号或用户 ID" @keyup.enter="load(true)"/></label><label class="field compact-field"><span>状态</span><select v-model="filters.status" @change="load(true)"><option value="all">全部状态</option><option v-for="(v,k) in STATUS" :key="k" :value="k">{{v[0]}}</option></select></label><label class="field compact-field"><span>类型</span><select v-model="filters.type" @change="load(true)"><option value="all">全部类型</option><option v-for="(v,k) in TYPES" :key="k" :value="k">{{v}}</option></select></label><label class="field compact-field"><span>套餐</span><select v-model="filters.plan_id" @change="load(true)"><option value="">全部套餐</option><option v-for="p in plans" :key="p.id" :value="p.id">{{p.name}}</option></select></label><button class="btn btn-ghost" @click="load(true)">查询</button><button class="btn btn-ghost" :disabled="loading" @click="load()">刷新</button></div>
<div class="table-wrap order-table"><table><thead><tr><th>订单号</th><th>用户 / 套餐</th><th>类型周期</th><th>金额</th><th>支付信息</th><th>状态</th><th>创建时间</th><th class="right">操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="8" class="empty">正在加载订单…</td></tr><tr v-else-if="!orders.length"><td colspan="8" class="empty">暂无符合条件的订单</td></tr><tr v-for="o in orders" :key="o.id"><td><button class="link-btn" @click="openDetail(o)">{{o.trade_no}}</button><small>#{{o.id}}</small></td><td><strong>用户 #{{o.user_id}}</strong><small>{{o.plan?.name||`套餐 #${o.plan_id}`}}</small></td><td>{{TYPES[o.type]||'未知'}}<small>{{PERIODS[o.period]||o.period}}</small></td><td><strong>{{money(o.total_amount)}}</strong><small v-if="o.discount_amount">优惠 {{money(o.discount_amount)}}</small><small v-if="o.group_buy_discount_amount">拼团优惠 {{money(o.group_buy_discount_amount)}}</small></td><td><span>{{o.payment_id?`支付方式 #${o.payment_id}`:'未选择支付'}}</span><small v-if="o.paid_at">支付于 {{time(o.paid_at)}}</small></td><td><span class="status-pill" :class="status(o)[1]">{{status(o)[0]}}</span></td><td>{{time(o.created_at)}}</td><td class="actions"><button class="btn btn-ghost btn-sm" :disabled="busy===o.trade_no" @click="openDetail(o)">详情</button><button v-if="Number(o.status)===0" class="btn btn-primary btn-sm" :disabled="busy===o.trade_no" @click="act(o,'paid')">标记支付</button><button v-if="Number(o.status)===0" class="btn btn-danger btn-sm" :disabled="busy===o.trade_no" @click="act(o,'cancel')">取消订单</button></td></tr></tbody></table></div><div class="pagination"><span>共 {{page.total}} 条</span><button class="btn btn-ghost btn-sm" :disabled="page.current<=1||loading" @click="page.current--;load()">上一页</button><span>{{page.current}} / {{page.last}}</span><button class="btn btn-ghost btn-sm" :disabled="page.current>=page.last||loading" @click="page.current++;load()">下一页</button></div></section>
<div v-if="detail" class="modal-backdrop" @click.self="detail=null"><section class="modal-card order-detail"><div class="panel-head"><div><h2>订单详情</h2><p>{{detail.trade_no}}</p></div><button class="btn btn-ghost" @click="detail=null">关闭</button></div><div class="detail-summary"><span>状态<strong>{{status(detail)[0]}}</strong></span><span>订单类型<strong>{{TYPES[detail.type]||'未知'}}</strong></span><span>订单金额<strong>{{money(detail.total_amount)}}</strong></span><span>支付时间<strong>{{time(detail.paid_at)}}</strong></span></div><div class="order-detail-grid"><span>用户<strong>{{detail.user?.email||`#${detail.user_id}`}}</strong></span><span>套餐<strong>{{detail.plan?.name||`#${detail.plan_id}`}}</strong></span><span>订阅周期<strong>{{PERIODS[detail.period]||detail.period}}</strong></span><span>支付方式<strong>{{detail.payment_id?`#${detail.payment_id}`:'未选择'}}</strong></span><span>余额支付<strong>{{money(detail.balance_amount)}}</strong></span><span>手续费<strong>{{money(detail.handling_amount)}}</strong></span><span>优惠金额<strong>{{money(detail.discount_amount)}}</strong></span><span>拼团优惠<strong>{{money(detail.group_buy_discount_amount)}}</strong></span><span>回调编号<strong>{{detail.callback_no||'-'}}</strong></span><span>创建时间<strong>{{time(detail.created_at)}}</strong></span></div></section></div>
<div v-if="showAssign" class="modal-backdrop" @click.self="showAssign=false"><section class="modal-card order-assign"><div class="panel-head"><div><h2>人工分配订单</h2><p>创建待支付订单；如需立即开通，请创建后再执行“标记支付”。</p></div><button class="btn btn-ghost" @click="showAssign=false">关闭</button></div><div class="smart-form"><label class="field field-wide"><span>用户邮箱 *</span><input v-model.trim="assign.email" type="email" placeholder="user@example.com"/></label><label class="field"><span>套餐 *</span><select v-model="assign.plan_id" @change="syncAssignPeriod"><option v-for="p in plans" :key="p.id" :value="p.id">{{p.name}}</option></select></label><label class="field"><span>订阅周期 *</span><select v-model="assign.period" @change="syncAssignPeriod"><option v-for="p in assignPeriods" :key="p[0]" :value="p[0]">{{p[1]}}</option></select></label><label class="field"><span>订单金额（元） *</span><input v-model.number="assign.total_yuan" type="number" min="0" step="0.01"/></label></div><div class="modal-actions"><button class="btn btn-ghost" @click="showAssign=false">取消</button><button class="btn btn-primary" :disabled="assigning" @click="saveAssign">{{assigning?'创建中…':'创建订单'}}</button></div></section></div><div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div></section></template>
