<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get, post } from '../services/http';

const ACTIONS = [{value:'block',label:'阻断',hint:'拒绝匹配流量'},{value:'direct',label:'直连',hint:'不经过代理直接连接'},{value:'dns',label:'DNS',hint:'交给指定 DNS 处理'},{value:'proxy',label:'代理',hint:'转发到指定出站'}];
const routes = ref([]); const nodes = ref([]); const loading = ref(true); const saving = ref(false); const busyId = ref(null); const keyword = ref(''); const actionFilter = ref(''); const showForm = ref(false); const matchText = ref('');
const form = reactive(defaultForm()); const toast = reactive({ text:'', type:'success' });
function defaultForm(){return{id:null,remarks:'',match:[],action:'direct',action_value:''};}
function linkedNodes(route){return nodes.value.filter(node=>(node.route_ids||[]).map(Number).includes(Number(route.id)));}
const items=computed(()=>routes.value.map(route=>({...route,linkedNodes:linkedNodes(route)})));
const filtered=computed(()=>items.value.filter(item=>{const term=keyword.value.trim().toLowerCase();return(!term||`${item.remarks} ${(item.match||[]).join(' ')}`.toLowerCase().includes(term))&&(!actionFilter.value||item.action===actionFilter.value);}));
const stats=computed(()=>({total:routes.value.length,used:items.value.filter(item=>item.linkedNodes.length).length,rules:routes.value.reduce((sum,item)=>sum+(item.match||[]).length,0),blocked:routes.value.filter(item=>item.action==='block').length}));
function notify(text,type='success'){toast.text=text;toast.type=type;window.clearTimeout(notify.timer);notify.timer=window.setTimeout(()=>{toast.text='';},2800);}
async function load(){loading.value=true;try{const [routeData,nodeData]=await Promise.all([get('/server/route/fetch'),get('/server/manage/getNodes')]);routes.value=Array.isArray(routeData)?routeData:[];nodes.value=Array.isArray(nodeData)?nodeData:[];}catch(e){notify(e.message,'error');}finally{loading.value=false;}}
function createRoute(){Object.assign(form,defaultForm());matchText.value='';showForm.value=true;}
function editRoute(route){Object.assign(form,defaultForm(),route,{match:[...(route.match||[])]});matchText.value=form.match.join('\n');showForm.value=true;}
function closeForm(){showForm.value=false;Object.assign(form,defaultForm());matchText.value='';}
function useTemplate(type){const templates={cn:['geosite:cn','geoip:cn'],ads:['geosite:category-ads-all'],private:['geoip:private','domain_suffix:local'],stream:['geosite:netflix','geosite:disney','geosite:youtube']};const next=templates[type]||[];const current=matchText.value.split('\n').map(v=>v.trim()).filter(Boolean);matchText.value=[...new Set([...current,...next])].join('\n');}
async function save(){const matches=[...new Set(matchText.value.split('\n').map(v=>v.trim()).filter(Boolean))];if(!form.remarks.trim()||!matches.length)return notify('规则名称和匹配项不能为空','error');if(['dns','proxy'].includes(form.action)&&!String(form.action_value||'').trim())return notify(`${form.action==='dns'?'DNS':'代理'}动作需要填写动作值`,'error');saving.value=true;try{await post('/server/route/save',{...form,match:matches,action_value:form.action_value||null});notify(form.id?'路由规则已更新':'路由规则已创建');closeForm();await load();}catch(e){notify(e.message,'error');}finally{saving.value=false;}}
async function remove(route){if(route.linkedNodes.length)return notify(`该规则仍被 ${route.linkedNodes.length} 个节点引用，请先解除绑定`,'error');if(!window.confirm(`确定删除路由规则「${route.remarks}」？`))return;busyId.value=route.id;try{await post('/server/route/drop',{id:route.id});notify('路由规则已删除');await load();}catch(e){notify(e.message,'error');}finally{busyId.value=null;}}
function actionMeta(value){return ACTIONS.find(item=>item.value===value)||{label:value,hint:''};}
function matchKind(value){const prefix=String(value).split(':')[0];return({geosite:'站点集',geoip:'IP 集',domain:'域名',domain_suffix:'域名后缀',domain_keyword:'域名关键字',ip_cidr:'IP 网段',port:'端口'}[prefix]||'自定义');}
function time(value){return value?new Date(Number(value)*1000).toLocaleString('zh-CN',{hour12:false}):'—';}
onMounted(load);
</script>

<template><section class="page-stack">
  <div class="page-heading page-heading-row"><div><h1>路由管理</h1><p>按域名、IP、规则集或端口匹配流量，并决定阻断、直连、DNS 或代理动作。</p></div><button class="btn btn-primary" @click="createRoute"><AppIcon name="Plus" :size="16" />添加路由规则</button></div>
  <div class="stat-grid route-stats"><article class="stat-card"><span>路由规则</span><strong>{{stats.total}}</strong></article><article class="stat-card"><span>节点使用中</span><strong>{{stats.used}}</strong></article><article class="stat-card"><span>匹配项</span><strong>{{stats.rules}}</strong></article><article class="stat-card"><span>阻断规则</span><strong>{{stats.blocked}}</strong></article></div>
  <div class="route-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" placeholder="名称或匹配内容" /></label><label class="field compact-field"><span>路由动作</span><select v-model="actionFilter"><option value="">全部动作</option><option v-for="action in ACTIONS" :key="action.value" :value="action.value">{{action.label}}</option></select></label><button class="btn btn-ghost" :disabled="loading" @click="load">刷新</button></div>
  <div class="panel route-guide"><AppIcon name="Info" :size="18" /><span>规则更新后会自动通知已绑定节点同步配置；规则顺序由节点中的绑定顺序决定。</span></div>
  <div v-if="loading" class="panel settings-loading">正在加载路由规则…</div><div v-else-if="!filtered.length" class="panel settings-loading">暂无符合条件的路由规则</div>
  <div v-else class="route-grid"><article v-for="route in filtered" :key="route.id" class="panel route-card"><div class="route-card-head"><div class="route-icon" :class="route.action"><AppIcon :name="route.action==='block'?'ShieldX':route.action==='direct'?'MoveRight':route.action==='dns'?'Globe':'Route'" :size="21" /></div><div><h2>{{route.remarks}}</h2><span>#{{route.id}} · {{time(route.updated_at)}}</span></div><span class="route-action" :class="route.action">{{actionMeta(route.action).label}}</span></div><p class="route-action-hint">{{actionMeta(route.action).hint}}<code v-if="route.action_value"> → {{route.action_value}}</code></p><div class="route-matches"><span v-for="match in route.match" :key="match" :title="match"><small>{{matchKind(match)}}</small>{{match}}</span></div><div class="route-reference"><span>引用节点</span><strong>{{route.linkedNodes.length}}</strong><div><i v-for="node in route.linkedNodes.slice(0,4)" :key="node.id">{{node.name}}</i><i v-if="route.linkedNodes.length>4">+{{route.linkedNodes.length-4}}</i><small v-if="!route.linkedNodes.length">尚未绑定节点</small></div></div><div class="route-actions"><button class="btn btn-ghost btn-sm" @click="editRoute(route)">编辑规则</button><button class="btn btn-danger btn-sm" :disabled="route.linkedNodes.length||busyId===route.id" :title="route.linkedNodes.length?'请先在节点管理中解除引用':''" @click="remove(route)">删除</button></div></article></div>
  <div v-if="showForm" class="modal-backdrop" @click.self="closeForm"><section class="modal-card route-modal"><div class="panel-head"><div><h2>{{form.id?'编辑路由规则':'添加路由规则'}}</h2><p>每行填写一个匹配项，支持规则集、域名、IP 网段等格式。</p></div><button class="btn btn-ghost" @click="closeForm">关闭</button></div><div class="smart-form"><label class="field field-wide"><span>规则名称</span><input v-model.trim="form.remarks" placeholder="例如：国内流量直连" /></label><label class="field"><span>执行动作</span><select v-model="form.action"><option v-for="action in ACTIONS" :key="action.value" :value="action.value">{{action.label}} — {{action.hint}}</option></select></label><label class="field"><span>动作值</span><input v-model.trim="form.action_value" :disabled="['block','direct'].includes(form.action)" :placeholder="form.action==='dns'?'DNS 服务器标签':form.action==='proxy'?'代理出站标签':'当前动作无需填写'" /><small>DNS 和代理动作必填</small></label><label class="field field-wide"><span>匹配项</span><div class="route-templates"><button type="button" @click="useTemplate('cn')">+ 国内规则</button><button type="button" @click="useTemplate('ads')">+ 广告拦截</button><button type="button" @click="useTemplate('private')">+ 私有网络</button><button type="button" @click="useTemplate('stream')">+ 流媒体</button></div><textarea v-model="matchText" rows="12" placeholder="geosite:cn&#10;geoip:cn&#10;domain_suffix:example.com&#10;ip_cidr:10.0.0.0/8" /><small>重复项和空行会在保存时自动清理。</small></label></div><div class="route-format-help"><strong>常用格式</strong><code>geosite:cn</code><code>geoip:private</code><code>domain:example.com</code><code>domain_suffix:example.com</code><code>ip_cidr:10.0.0.0/8</code></div><div class="modal-actions"><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'保存中…':'保存路由规则'}}</button></div></section></div>
  <div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div>
</section></template>
