<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import AppIcon from '../components/AppIcon.vue';
import { get, post } from '../services/http';

const machines = ref([]); const loading = ref(true); const saving = ref(false); const busyId = ref(null); const keyword = ref(''); const statusFilter = ref('all');
const showForm = ref(false); const detail = ref(null); const nodes = ref([]); const history = ref([]); const detailLoading = ref(false); const credential = reactive({ token: '', command: '' });
const toast = reactive({ text: '', type: 'success' }); const form = reactive(defaultForm());
function defaultForm() { return { id: null, name: '', notes: '', is_active: true }; }
const filtered = computed(() => machines.value.filter((item) => { const term = keyword.value.trim().toLowerCase(); return (!term || `${item.name} ${item.notes || ''}`.toLowerCase().includes(term)) && (statusFilter.value === 'all' || Boolean(item.is_active) === (statusFilter.value === '1')); }));
const stats = computed(() => ({ total: machines.value.length, online: machines.value.filter(isOnline).length, nodes: machines.value.reduce((sum, item) => sum + Number(item.servers_count || 0), 0) }));
function notify(text, type = 'success') { toast.text = text; toast.type = type; window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => { toast.text = ''; }, 2800); }
function isOnline(item) { return Boolean(item.is_active) && Number(item.last_seen_at || 0) > Math.floor(Date.now() / 1000) - 180; }
function percent(used, total) { return total ? Math.min(100, Math.round(Number(used || 0) / Number(total) * 100)) : 0; }
function bytes(value) { const n = Number(value || 0); if (!n) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const i = Math.min(Math.floor(Math.log(n) / Math.log(1024)), units.length - 1); return `${(n / 1024 ** i).toFixed(i > 2 ? 1 : 0)} ${units[i]}`; }
function speed(value) { return `${bytes(value)}/s`; }
function time(value) { return value ? new Date(Number(value) * 1000).toLocaleString('zh-CN', { hour12: false }) : '从未连接'; }
async function load() { loading.value = true; try { const data = await get('/server/machine/fetch'); machines.value = Array.isArray(data) ? data : []; } catch (e) { notify(e.message, 'error'); } finally { loading.value = false; } }
function createMachine() { Object.assign(form, defaultForm()); credential.token = ''; credential.command = ''; showForm.value = true; }
function editMachine(item) { Object.assign(form, defaultForm(), item); credential.token = ''; credential.command = ''; showForm.value = true; }
function closeForm() { showForm.value = false; Object.assign(form, defaultForm()); }
async function save() { if (!form.name.trim()) return notify('机器名称不能为空', 'error'); saving.value = true; try { const result = await post('/server/machine/save', { ...form, is_active: Boolean(form.is_active) }); if (!form.id && result) { form.id = result.id; credential.token = result.token || ''; credential.command = result.install_command || ''; notify('机器已创建，请保存安装凭据'); } else { notify('机器配置已更新'); closeForm(); } await load(); } catch (e) { notify(e.message, 'error'); } finally { saving.value = false; } }
async function openDetail(item) { detail.value = item; detailLoading.value = true; nodes.value = []; history.value = []; try { const [nodeData, historyData] = await Promise.all([get('/server/machine/nodes', { machine_id: item.id }), get('/server/machine/history', { machine_id: item.id, range_hours: 24, limit: 120 })]); nodes.value = Array.isArray(nodeData) ? nodeData : []; history.value = Array.isArray(historyData) ? historyData : []; } catch (e) { notify(e.message, 'error'); } finally { detailLoading.value = false; } }
async function showCredentials(item) { busyId.value = item.id; try { const [tokenData, commandData] = await Promise.all([get('/server/machine/getToken', { id: item.id }), get('/server/machine/installCommand', { id: item.id })]); Object.assign(form, defaultForm(), item); credential.token = tokenData.token || ''; credential.command = commandData.command || ''; showForm.value = true; } catch (e) { notify(e.message, 'error'); } finally { busyId.value = null; } }
async function resetToken() { if (!window.confirm('确定重置机器 Token？旧 Token 会立即失效，机器代理必须重新配置。')) return; saving.value = true; try { const data = await post('/server/machine/resetToken', { id: form.id }); credential.token = data.token; const commandData = await get('/server/machine/installCommand', { id: form.id }); credential.command = commandData.command || ''; notify('Token 已重置'); } catch (e) { notify(e.message, 'error'); } finally { saving.value = false; } }
async function remove(item) { if (!window.confirm(`确定删除机器「${item.name}」？关联的 ${item.servers_count || 0} 个节点将自动解除绑定。`)) return; busyId.value = item.id; try { await post('/server/machine/drop', { id: item.id }); notify('机器已删除'); await load(); } catch (e) { notify(e.message, 'error'); } finally { busyId.value = null; } }
async function copy(value, label) { try { await navigator.clipboard.writeText(value); notify(`${label}已复制`); } catch { notify('复制失败，请手动复制', 'error'); } }
onMounted(load);
</script>

<template>
  <section class="page-stack">
    <div class="page-heading page-heading-row"><div><h1>服务器管理</h1><p>管理机器代理、安装凭据、关联节点与实时资源负载。</p></div><button class="btn btn-primary" @click="createMachine"><AppIcon name="Plus" :size="16" />添加服务器</button></div>
    <div class="stat-grid machine-stats"><article class="stat-card"><span>服务器总数</span><strong>{{ stats.total }}</strong></article><article class="stat-card"><span>在线服务器</span><strong>{{ stats.online }}</strong></article><article class="stat-card"><span>关联节点</span><strong>{{ stats.nodes }}</strong></article></div>
    <div class="machine-toolbar"><label class="filter-input"><span>搜索</span><input v-model="keyword" placeholder="服务器名称或备注" /></label><label class="field compact-field"><span>启用状态</span><select v-model="statusFilter"><option value="all">全部状态</option><option value="1">已启用</option><option value="0">已停用</option></select></label><button class="btn btn-ghost" :disabled="loading" @click="load">刷新</button></div>
    <div v-if="loading" class="panel settings-loading">正在加载服务器…</div><div v-else-if="!filtered.length" class="panel settings-loading">暂无符合条件的服务器</div>
    <div v-else class="machine-grid"><article v-for="item in filtered" :key="item.id" class="panel machine-card"><div class="machine-head"><div class="machine-icon"><AppIcon name="Server" :size="22" /></div><div><h2>{{ item.name }}</h2><span>#{{ item.id }} · {{ item.servers_count || 0 }} 个节点</span></div><div class="machine-state"><i :class="{ online: isOnline(item) }" /><span>{{ isOnline(item) ? '在线' : item.is_active ? '离线' : '已停用' }}</span></div></div><p class="machine-notes">{{ item.notes || '暂无备注' }}</p>
      <div class="load-grid"><div><span>CPU <b>{{ Number(item.load_status?.cpu || 0).toFixed(1) }}%</b></span><i><em :style="{ width: `${Number(item.load_status?.cpu || 0)}%` }" /></i></div><div><span>内存 <b>{{ percent(item.load_status?.mem?.used, item.load_status?.mem?.total) }}%</b></span><i><em :style="{ width: `${percent(item.load_status?.mem?.used, item.load_status?.mem?.total)}%` }" /></i></div><div><span>磁盘 <b>{{ percent(item.load_status?.disk?.used, item.load_status?.disk?.total) }}%</b></span><i><em :style="{ width: `${percent(item.load_status?.disk?.used, item.load_status?.disk?.total)}%` }" /></i></div></div>
      <div class="machine-meta"><span>最后心跳：{{ time(item.last_seen_at) }}</span><span v-if="item.load_status?.net">↓ {{ speed(item.load_status.net.in_speed) }}　↑ {{ speed(item.load_status.net.out_speed) }}</span></div><div class="machine-actions"><button class="btn btn-ghost btn-sm" @click="openDetail(item)">节点与负载</button><button class="btn btn-ghost btn-sm" :disabled="busyId === item.id" @click="showCredentials(item)">安装凭据</button><button class="btn btn-ghost btn-sm" @click="editMachine(item)">编辑</button><button class="btn btn-danger btn-sm" :disabled="busyId === item.id" @click="remove(item)">删除</button></div></article></div>
    <div v-if="showForm" class="modal-backdrop" @click.self="closeForm"><section class="modal-card machine-modal"><div class="panel-head"><div><h2>{{ form.id ? '服务器配置' : '添加服务器' }}</h2><p>机器代理连接面板后会自动上报负载与心跳。</p></div><button class="btn btn-ghost" @click="closeForm">关闭</button></div><div class="smart-form"><label class="field"><span>服务器名称</span><input v-model.trim="form.name" placeholder="例如：香港入口机" /></label><label class="field"><span>启用状态</span><ToggleSwitch v-model="form.is_active" :true-value="true" :false-value="false" on-label="已启用" off-label="已停用" /></label><label class="field field-wide"><span>备注</span><textarea v-model="form.notes" rows="3" placeholder="机房、用途或维护说明" /></label></div>
      <div v-if="credential.token || credential.command" class="credential-box"><div class="credential-warning">Token 属于敏感凭据，请仅在受信任的服务器上使用。</div><label v-if="credential.token"><span>机器 Token</span><div><code>{{ credential.token }}</code><button class="btn btn-ghost btn-sm" @click="copy(credential.token, 'Token')">复制</button></div></label><label v-if="credential.command"><span>一键安装命令</span><div><code>{{ credential.command }}</code><button class="btn btn-ghost btn-sm" @click="copy(credential.command, '安装命令')">复制</button></div></label></div><div class="modal-actions"><button v-if="form.id" class="btn btn-danger" :disabled="saving" @click="resetToken">重置 Token</button><button class="btn btn-primary" :disabled="saving" @click="save">{{ saving ? '保存中…' : form.id ? '保存配置' : '创建服务器' }}</button></div></section></div>
    <div v-if="detail" class="modal-backdrop" @click.self="detail = null"><section class="modal-card machine-detail"><div class="panel-head"><div><h2>{{ detail.name }} · 运行详情</h2><p>最近 24 小时负载采样与当前关联节点。</p></div><button class="btn btn-ghost" @click="detail = null">关闭</button></div><div v-if="detailLoading" class="settings-loading">正在加载运行数据…</div><template v-else><h3>关联节点（{{ nodes.length }}）</h3><div v-if="nodes.length" class="machine-node-list"><div v-for="node in nodes" :key="node.id"><strong>{{ node.name }}</strong><code>{{ node.host }}:{{ node.port }}</code><span>{{ node.type }}</span><span class="status-pill" :class="{ off: !node.enabled }">{{ node.enabled ? '已启用' : '已停用' }}</span></div></div><div v-else class="settings-loading">暂无关联节点</div><h3>负载历史（{{ history.length }} 条）</h3><div v-if="history.length" class="history-table"><table><thead><tr><th>时间</th><th>CPU</th><th>内存</th><th>磁盘</th><th>网络</th></tr></thead><tbody><tr v-for="row in history.slice(-30).reverse()" :key="row.recorded_at"><td>{{ time(row.recorded_at) }}</td><td>{{ Number(row.cpu).toFixed(1) }}%</td><td>{{ percent(row.mem_used, row.mem_total) }}%</td><td>{{ percent(row.disk_used, row.disk_total) }}%</td><td>↓ {{ speed(row.net_in_speed) }} / ↑ {{ speed(row.net_out_speed) }}</td></tr></tbody></table></div><div v-else class="settings-loading">暂无负载历史</div></template></section></div>
    <div v-if="toast.text" class="toast" :class="{ error: toast.type === 'error' }">{{ toast.text }}</div>
  </section>
</template>
