<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { menuGroups } from '../config/menu';
import { get, post } from '../services/http';
import { confirmAction } from '../services/confirm';
import ToggleSwitch from '../components/ToggleSwitch.vue';

const rows=ref([]),loading=ref(true),saving=ref(false),showForm=ref(false),generated=ref('');
const toast=reactive({text:'',type:'success'});
const permissionItems=computed(()=>menuGroups.flatMap(g=>g.items.map(i=>({...i,group:g.title||'概览'}))).filter(i=>!['/system/admin-lock','/system/temporary-access'].includes(i.path)));
const blank=()=>({id:null,email:'',password:'',expires_at:new Date(Date.now()+2*3600000).toISOString().slice(0,16),max_logins:10,active:true,allowed_ips_text:'',permissions:{'/dashboard':'read'}});
const form=reactive(blank());
function notify(text,type='success'){toast.text=text;toast.type=type;clearTimeout(notify.t);notify.t=setTimeout(()=>toast.text='',3500)}
function fmt(v){if(!v)return '—';const d=new Date(typeof v==='number'?v*1000:v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('zh-CN',{hour12:false})}
function usable(r){return r.active&&new Date(r.expires_at).getTime()>Date.now()&&Number(r.login_count)<=Number(r.max_logins)}
async function load(){loading.value=true;try{rows.value=await get('/temporary-access/fetch')}catch(e){notify(e.message,'error')}finally{loading.value=false}}
function open(row=null){Object.assign(form,blank());generated.value='';if(row){Object.assign(form,{id:row.id,email:row.user?.email||'',expires_at:new Date(row.expires_at).toISOString().slice(0,16),max_logins:row.max_logins,active:Boolean(row.active),allowed_ips_text:(row.allowed_ips||[]).join('\n'),permissions:{...(row.permissions||{})}})}showForm.value=true}
function togglePermission(path,checked){if(checked)form.permissions[path]='read';else delete form.permissions[path]}
async function save(){saving.value=true;try{const data=await post('/temporary-access/save',{id:form.id,email:form.email,password:form.password||null,expires_at:new Date(form.expires_at).toISOString(),max_logins:Number(form.max_logins),active:form.active,allowed_ips:form.allowed_ips_text.split(/\s+/).map(v=>v.trim()).filter(Boolean),permissions:form.permissions});generated.value=data.generated_password||'';notify('临时访问已保存');await load();if(!generated.value)showForm.value=false}catch(e){notify(e.message,'error')}finally{saving.value=false}}
async function revoke(row){if(!await confirmAction({title:'撤销临时访问',message:`立即撤销 ${row.user?.email} 的全部会话？`,danger:true,confirmText:'立即撤销'}))return;await post('/temporary-access/revoke',{id:row.id});notify('已撤销');load()}
async function remove(row){if(!await confirmAction({title:'删除临时账号',message:`删除 ${row.user?.email} 及其访问记录关联？`,danger:true,confirmText:'删除账号'}))return;await post('/temporary-access/drop',{id:row.id});notify('已删除');load()}
onMounted(load);
</script>
<template><section class="page-stack"><div class="page-heading page-heading-row"><div><h1>临时访问</h1><p>为运维人员创建限时账号，并按页面分配只读或管理权限。</p></div><button class="btn btn-primary" @click="open()">创建临时账号</button></div>
<div class="stat-grid access-stats"><article class="panel stat-card"><span>账号总数</span><strong>{{rows.length}}</strong></article><article class="panel stat-card"><span>当前有效</span><strong>{{rows.filter(usable).length}}</strong></article><article class="panel stat-card"><span>已过期/撤销</span><strong>{{rows.filter(r=>!usable(r)).length}}</strong></article></div>
<div class="panel table-wrap"><table><thead><tr><th>账号</th><th>有效期</th><th>登录次数</th><th>IP 限制</th><th>页面权限</th><th>状态</th><th class="right">操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="7" class="empty">正在加载…</td></tr><tr v-else-if="!rows.length"><td colspan="7" class="empty">暂无临时账号</td></tr><tr v-for="r in rows" :key="r.id"><td><strong>{{r.user?.email}}</strong><small>创建人：{{r.creator?.email||'—'}}</small></td><td>{{fmt(r.expires_at)}}</td><td>{{r.login_count}} / {{r.max_logins}}</td><td>{{r.allowed_ips?.length?r.allowed_ips.join('、'):'不限 IP'}}</td><td>{{Object.keys(r.permissions||{}).length}} 个页面</td><td><span class="status-pill" :class="{off:!usable(r)}">{{usable(r)?'有效':'不可用'}}</span></td><td class="actions"><button class="btn btn-ghost btn-sm" @click="open(r)">编辑</button><button class="btn btn-ghost btn-sm" @click="revoke(r)">撤销</button><button class="btn btn-danger btn-sm" @click="remove(r)">删除</button></td></tr></tbody></table></div>
<div v-if="showForm" class="modal-backdrop" @click.self="showForm=false"><section class="modal-card access-modal"><div class="panel-head"><div><h2>{{form.id?'编辑临时访问':'创建临时访问'}}</h2><p>留空密码将自动生成；保存后仅显示一次。</p></div><button class="btn btn-ghost" @click="showForm=false">关闭</button></div><div v-if="generated" class="generated-credential"><strong>请立即保存初始密码</strong><code>{{generated}}</code><small>关闭窗口后将无法再次查看。</small></div><template v-else><div class="smart-form"><label class="field"><span>登录邮箱</span><input v-model.trim="form.email" type="email"/></label><label class="field"><span>{{form.id?'重置密码':'初始密码'}}</span><input v-model="form.password" type="password" minlength="12" placeholder="留空自动生成"/></label><label class="field"><span>到期时间</span><input v-model="form.expires_at" type="datetime-local"/></label><label class="field"><span>最大登录次数</span><input v-model.number="form.max_logins" type="number" min="1" max="1000"/></label><label class="field"><span>账号状态</span><ToggleSwitch v-model="form.active" on-label="已启用" off-label="已停用"/></label><label class="field"><span>允许 IP</span><textarea v-model="form.allowed_ips_text" rows="3" placeholder="每行一个；留空不限制"/></label></div><h3 class="access-permission-title">页面权限</h3><div class="permission-grid"><label v-for="item in permissionItems" :key="item.path"><input type="checkbox" :checked="Boolean(form.permissions[item.path.split('?')[0]])" @change="togglePermission(item.path.split('?')[0],$event.target.checked)"/><span><strong>{{item.title}}</strong><small>{{item.group}}</small></span><select v-if="form.permissions[item.path.split('?')[0]]" v-model="form.permissions[item.path.split('?')[0]]"><option value="read">只读</option><option value="write">可管理</option></select></label></div><div class="modal-actions"><button class="btn btn-primary" :disabled="saving||!form.email||!Object.keys(form.permissions).length" @click="save">{{saving?'保存中…':'保存临时访问'}}</button></div></template></section></div><div v-if="toast.text" class="toast" :class="{error:toast.type==='error'}">{{toast.text}}</div></section></template>
